### PR TITLE
Modalities in aliases and let-bindings

### LINKED ISSUE #7987: Allow erased `let`s
Agda currently does not recognize erasure annotations in module parameter `let`s:
```agda
{-# OPTIONS --erasure #-}

open import Agda.Builtin.Nat

module _ (@0 n : Nat) (let @0 m = suc n) where

  @0 k : Nat
  k = m

-- error: [VariableIsErased]
-- Variable n is declared erased, so it cannot be used here
-- when checking that the expression n has type Nat

-- warning: -W[no]MisplacedAttributes
-- A function clause cannot have attributes
```
The warning indicates a weakness in the parser.

Update: seems like erased `let`s are generally not supported.

This also ignores the erasure annotation:
```agda
_ = let @0 S = Set in S → S
```

### LINKED ISSUE #7989: Weird error for irrelevant clause
Trying to write an irrelevant alias:
```agda
. A = Set
```
```
Missing type signature for left hand side .A
when scope checking the declaration
  .A = Set
```

### PR DESCRIPTION
**Pull request by andreasabel**
Fixes:
- #7987 
- #7989

Closes #7987.  Closes #7989.

It is implemented by allowing attributes in function clauses.  
The consistency of attributes (among several clauses and the type signature) is ~~not checked yet.~~ checked in the nicifier.  (Most work is done in the nicifier.)
Modalities from aliases are pushed into the type signature already before the type-checker.

### CODE REVIEW

File: src/full/Agda/Syntax/Concrete.hs [hunk 1]
```diff
@@ -512,7 +512,7 @@ data Declaration
   | FieldSig IsInstance TacticAttribute Name (Arg Expr)
   | Generalize KwRange [TypeSignature] -- ^ Variables to be generalized, can be hidden and/or irrelevant.
   | Field KwRange [FieldSignature]
-  | FunClause LHS RHS WhereClause Catchall
+  | FunClause ArgInfo LHS RHS WhereClause Catchall -- ^ Only 'Relevance' is used in 'ArgInfo' so far.
```
Comment (andreasabel) [inline src/full/Agda/Syntax/Concrete.hs]: That should say "Only `Modality`".

File: src/full/Agda/Syntax/Concrete.hs [hunk 2]
```diff
@@ -1377,7 +1377,7 @@ instance NFData Declaration where
   rnf (FieldSig a b c d)      = rnf a `seq` rnf b `seq` rnf c `seq` rnf d
   rnf (Generalize _ a)        = rnf a
   rnf (Field _ fs)            = rnf fs
-  rnf (FunClause a b c d)     = rnf a `seq` rnf b `seq` rnf c `seq` rnf d
+  rnf (FunClause a b c d e)     = rnf a `seq` rnf b `seq` rnf c `seq` rnf d `seq` rnf e
```
Comment (andreasabel) [inline src/full/Agda/Syntax/Concrete.hs]: Delete space before =.

File: src/full/Agda/Syntax/Concrete/Definitions.hs [hunk 3]
```diff
@@ -337,7 +337,7 @@ niceDeclarations fixs ds = do
               -- Subcase: The lhs is single identifier (potentially anonymous).
               -- Treat it as a function clause without a type signature.
               LHS p [] [] | Just x <- isSingleIdentifierP p -> do
-                d  <- mkFunDef (setOrigin Inserted defaultArgInfo) termCheck covCheck x Nothing $ singleton d -- fun def without type signature is relevant
+                d  <- mkFunDef (setOrigin Inserted ai) termCheck covCheck x Nothing $ singleton d -- fun def without type signature can also be irrelevant
```
Comment (andreasabel) [inline src/full/Agda/Syntax/Concrete/Definitions.hs]: Comment should say "can have modality".

File: src/full/Agda/Syntax/Concrete/Definitions.hs [hunk 4]
```diff
@@ -769,26 +769,30 @@ niceDeclarations fixs ds = do
...
-    mkClauses x (Pragma (CatchallPragma r) : cs) catchall = do
+    mkClauses ai x (Pragma (CatchallPragma r) : cs) catchall = do
       -- Warn about consecutive CATCHALL pragmas
       unless (null catchall) $ declarationWarning $ InvalidCatchallPragma r
-      mkClauses x cs (YesCatchall r)
+      mkClauses ai x cs (YesCatchall r)
 
-    mkClauses x (FunClause lhs rhs wh ca : cs) catchall
+    -- mkClauses ai1 x (FunClause ai2 lhs rhs wh ca : cs) catchall
+    --   | not (null ai2 || ai1 == ai2) = __IMPOSSIBLE__ -- TODO: declarationWarning $ InvalidModality ai
```
Comment (andreasabel) [inline src/full/Agda/Syntax/Concrete/Definitions.hs]: Remove this commented code.

File: src/full/Agda/Syntax/Concrete/Definitions.hs [hunk 5]
```diff
@@ -807,7 +811,14 @@ niceDeclarations fixs ds = do
...
         subClauses _  = __IMPOSSIBLE__
-    mkClauses _ _ _ = __IMPOSSIBLE__
+    mkClauses _ _ _ _ = __IMPOSSIBLE__
+
+    reconcileArgInfo :: ArgInfo -> ArgInfo -> ArgInfo
+    reconcileArgInfo ai1 ai2
+      | null ai1 = ai2
+      | null ai2 = ai1
+      | let r1 = getRelevance ai1, let r2 = getRelevance ai2 =
+          if sameRelevance r1 r2 then ai1 else setRelevance (max r1 r2) ai1
```
Comment (andreasabel) [inline src/full/Agda/Syntax/Concrete/Definitions.hs]: This should be updated to work with other modalities.
Also, we should deal with conflicting attributes.

File: src/full/Agda/Syntax/Concrete/Pretty.hs [hunk 6]
```diff
@@ -391,8 +391,9 @@ instance Pretty Declaration where
       sep [ "field"
           , nest 2 $ vcat (map pretty fs)
           ]
-    FunClause lhs rhs wh _ ->
-      sep [ pretty lhs
+    FunClause ai lhs rhs wh _ ->
+      sep [ pretty (getRelevance ai)
```
Comment (andreasabel) [inline src/full/Agda/Syntax/Concrete/Pretty.hs]: Extend to other modalities.

File: src/full/Agda/Syntax/Translation/AbstractToConcrete.hs [hunk 7]
```diff
@@ -913,7 +913,7 @@ instance ToConcrete A.Expr where
                 return [p] -- __IMPOSSIBLE__
                   -- Andreas, this is actually not impossible,
                   -- my strictification exposed this sleeping bug
-          let decl2clause (C.FunClause (C.LHS p [] []) rhs C.NoWhere ca) = do
+          let decl2clause (C.FunClause ai (C.LHS p [] []) rhs C.NoWhere ca) = do
```
Comment (andreasabel) [inline src/full/Agda/Syntax/Translation/AbstractToConcrete.hs:916]: Should this `ai` be kept somewhere (looks like it is discarded).  Or is it irrelevant for extended lambdas?

File: src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs [hunk 8]
```diff
@@ -1493,7 +1493,15 @@ instance ToAbstract LetDef where
...
-      (x', e) <- letToAbstract cl
+      (ai, x', e) <- letToAbstract cl
+
+      -- Andreas, 2025-07-09, issue #7989.
+      -- Check that arginfo of clause matches the one of the declaration.
+      let declRel = getRelevance info
+          defRel  = getRelevance ai
+      unless (null ai || sameRelevance declRel defRel) $
+        setCurrentRange defRel $
+          warning $ FixingRelevance "Correcting relevance attribute in clause" defRel declRel
```
Comment (andreasabel) [inline src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs]: Revisit this for other modalities.

File: src/full/Agda/TypeChecking/Rules/Def.hs [hunk 9]
```diff
@@ -120,7 +120,10 @@ checkFunDef i name cs = do
               -- happens.
               whenM (isOpenMeta <$> lookupMetaInstantiation x) $
                 setCurrentRange i $ warning $ MissingTypeSignatureForOpaque name (Info.defOpaque i)
-              checkFunDef' t info Nothing Nothing i name cs
+              checkFunDef' t info' Nothing Nothing i name cs
+            where
+              -- Copy relevance info from ai
+              info' = mapRelevance (max (getRelevance ai)) info
```
Comment (andreasabel) [inline src/full/Agda/TypeChecking/Rules/Def.hs]: Revisit this for other modalities.

File: src/full/Agda/TypeChecking/Rules/Def.hs [hunk 10]
```diff
@@ -706,8 +710,21 @@ checkClause
...
+
+ --  -- Check that we do not ignore other modality info
+ --  unless (null $ setRelevance empty ai) __IMPOSSIBLE__
+
+  unlessNull (getRelevance ai) \ r' -> do
+    r <- asksTC envRelevance
+    unless (sameRelevance r r') do
+      -- Warn about ignored relevance
+      setCurrentRange r' do
+        warning $ FixingRelevance "contradicting declared relevance" r' r
```
Comment (andreasabel) [inline src/full/Agda/TypeChecking/Rules/Def.hs]: Revisit this for other modalities.
(Can this warning be triggered?)

File: src/full/Agda/Syntax/Translation/AbstractToConcrete.hs (hunk 7 above)
Comment (andreasabel) [reply src/full/Agda/Syntax/Translation/AbstractToConcrete.hs:916]: Maybe not so important.
