### PR TITLE
Fix #8231: Check relevance in `PTerm` matching

### LINKED ISSUE #8231: Rewrite rule matching does not respect irrelevance
The rewrite rule fails to apply in the following example, despite the fact that `f false` and `f true` are definitionally equal by irrelevance.
```agda
{-# OPTIONS --rewriting #-}

open import Agda.Builtin.Bool
open import Agda.Builtin.Equality
import Agda.Builtin.Equality.Rewrite

postulate
  A : Set
  x : A
  f : .Bool → A
  eq : f false ≡ x

{-# REWRITE eq #-}

bug : f true ≡ x
bug = refl
```
Tested in Agda versions 2.8.0-3d04bac and 2.9.0-4cd398e.

### PR DESCRIPTION
**Pull request by NathanielB123**
Fix #8231: We need to check relevance when matching against a `PTerm` and skip the conversion test when the relevance is irrelevant.

### CODE REVIEW

File: src/full/Agda/TypeChecking/Rewriting/NonLinMatch.hs [hunk 1]
```diff
@@ -394,7 +394,9 @@ instance Match NLPat Term where
             Nothing -> no ""
         v -> maybeBlock v
       PTerm u -> traceSDoc "rewriting.match" 60 ("matching a PTerm" <+> addContext gamma (addContext k $ prettyTCM u)) $
-        tellEq gamma k t u v
+        -- #8231: We need to skip testing conversion if we are matching at
+        -- unusable irrelevance
+        when (usableRelevance r) $ tellEq gamma k t u v
```
Comment (cppio) [inline src/full/Agda/TypeChecking/Rewriting/NonLinMatch.hs]: Shouldn't this be `unless (isIrrelevant r)` to correctly handle shape-irrelevant.

Comment (NathanielB123) [reply src/full/Agda/TypeChecking/Rewriting/NonLinMatch.hs]: Ah yes, good point.

Comment (cppio) [reply src/full/Agda/TypeChecking/Rewriting/NonLinMatch.hs]: With the change to `when (usableRelevance r)`, `bad` is incorrectly accepted:
```agda
{-# OPTIONS --rewriting #-}

open import Agda.Builtin.Nat
open import Agda.Builtin.Equality
import Agda.Builtin.Equality.Rewrite

data T : ..Nat → Set where
  a : T 0
  b c : T 1

f : ∀ ..n → T n → T n
f 0 a = a
f 1 b = c
f 1 c = b

eq : ∀ x → f 0 x ≡ x
eq a = refl

{-# REWRITE eq #-}

bad : ∀ x → f 1 x ≡ x
bad _ = refl

fail : {A : Set} → A
fail with () <- bad b
```

Comment (NathanielB123) [reply src/full/Agda/TypeChecking/Rewriting/NonLinMatch.hs]: Fixed, and added this example as a failing test case - thanks!

**Review by andreasabel — APPROVED** [review]

**Review by andreasabel — APPROVED** [review]
Thanks!

**Comment by andreasabel** [comment]
@jespercockx : Do you want to review?

**Review by jespercockx — APPROVED** [review]
