### PR TITLE
[ fix #4696 ] Print file & line of raised error at verbosity 2

### LINKED ISSUE #4696: Add a debug mode printing the source file & position an error was raised from
At the moment we get really good location with `__IMPOSSIBLE__` but are left
to our own devices when we encounter an unexpected error. My workflow usually
amounts to:

* grepping for the error message
* finding the corresponding error constructor
* grepping for the constructor
* identifying the source (among potentially many) of the error

We should be able to have a verbosity level for `error` telling us exactly
where to look. It should not be too much work as we are only using a small
set of functions to raise errors.

I'll assign myself & aim to do it by the end of this AIM but if someone looking
for a sprint wants to preempt this issue, be my guest.

### PR DESCRIPTION
**Pull request by gallais**

### CODE REVIEW

**Comment by gallais** [comment]
I am really puzzled: I do get appropriate debug info with source file & location
where the type error / warning was raised but not all the time. Non fatal errors
(I have experienced it with `TerminationIssue` and `UnsolvedMetas` so far) seem
to somehow escape the reporting.

This is already a useful feature as is but it would be nice to understand what
is happening here & get total coverage of errors & warnings.

File: src/full/Agda/Syntax/Concrete/Definitions.hs [hunk 1]
```diff
@@ -164,8 +165,18 @@ type NiceTypeSignature  = NiceDeclaration
 data Clause = Clause Name Catchall LHS RHS WhereClause [Clause]
     deriving (Data, Show)
 
+-- | Exception with File and Line source
+data DeclarationException = DeclarationException
+  { deFileLine   :: (String, Int)
```
Comment (andreasabel) [inline src/full/Agda/Syntax/Concrete/Definitions.hs]: Please introduce a data type for the AgdaSourceErrorLocation (rather than using a pair). E.g.
```haskell
data AgdaSourceErrorLocation = AgdaSourceErrorLocation
  { slocFile :: String  -- ^ File of the Agda source code.
  , slocLine :: Int     -- ^ Line number in this file
  }
```
See the style guide (don't use tuples!).

File: src/full/Agda/Syntax/Concrete/Definitions.hs [hunk 2]
```diff
@@ -183,8 +194,20 @@ data DeclarationException
     deriving (Data, Show)
 
 
+data DeclarationWarning = DeclarationWarning
+  { dwFileLine :: (String, Int)
```
Comment (andreasabel) [inline src/full/Agda/Syntax/Concrete/Definitions.hs]: Use it here.

File: src/full/Agda/Syntax/Scope/Monad.hs [hunk 3]
```diff
@@ -76,6 +78,11 @@ printLocals v s = verboseS "scope.top" v $ do
   locals <- getLocalVars
   reportSLn "scope.top" v $ s ++ " " ++ prettyShow locals
 
+scopeWarning :: HasCallStack => DeclarationWarning' -> ScopeM ()
+scopeWarning d = withFileAndLine' (freezeCallStack callStack) $ \ file line ->
+  warning' (file, line)  $ NicifierIssue $
```
Comment (andreasabel) [inline src/full/Agda/Syntax/Scope/Monad.hs]: Here.

File: src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs [hunk 4]
```diff
@@ -106,17 +107,21 @@ import Agda.ImpossibleTest (impossibleTest)
 
 -- notAModuleExpr e = typeError $ NotAModuleExpr e
 
-notAnExpression :: C.Expr -> ScopeM A.Expr
-notAnExpression e = typeError $ NotAnExpression e
+notAnExpression :: HasCallStack => C.Expr -> ScopeM A.Expr
+notAnExpression e = withFileAndLine' (freezeCallStack callStack) $ \ file line ->
+  typeError' (file, line) $ NotAnExpression e
```
Comment (andreasabel) [inline src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs]: Here...

File: src/full/Agda/Syntax/Concrete/Definitions.hs [hunk 5]
```diff
@@ -183,8 +194,20 @@ data DeclarationException
...
+  , dwWarning  :: DeclarationWarning'
+  } deriving (Show, Data)
+
+declarationWarning' :: HasCallStack => (String, Int) -> DeclarationWarning' -> Nice ()
```
Comment (andreasabel) [inline src/full/Agda/Syntax/Concrete/Definitions.hs]: Here.

**Review by andreasabel — CHANGES_REQUESTED** [review]
Nice!

Please introduce a data type (with attached documentation) replacing `(String, Int)` for the sake of program comprehension.

File: src/full/Agda/TypeChecking/Errors.hs [hunk 6]
```diff
@@ -260,13 +260,13 @@ instance PrettyTCM TCErr where
     -- Gallais, 2016-05-14
     -- Given where `NonFatalErrors` are created, we know for a
     -- fact that ̀ws` is non-empty.
-    TypeError (file, line) _ Closure{ clValue = NonFatalErrors ws } -> do
+    TypeError (AgdaSourceErrorLocation file line) _ Closure{ clValue = NonFatalErrors ws } -> do
       reportSLn "error" 2 $ "Error raised in file " ++ file ++ " at line " ++ show line
```
Comment (andreasabel) [inline src/full/Agda/TypeChecking/Errors.hs]: Suggestion: define `Pretty AgdaSourceErrorLocation` and use it when reporting the location.
Should the location be printed as `<file>:<line>` which is the standard (and maybe be parseable by emacs modes etc.).

File: src/full/Agda/TypeChecking/Errors.hs [hunk 7]
```diff
@@ -260,13 +260,13 @@ instance PrettyTCM TCErr where
...
       foldr1 ($$) $ fmap prettyTCM ws
     -- Andreas, 2014-03-23
     -- This use of withTCState seems ok since we do not collect
     -- Benchmark info during printing errors.
-    TypeError (file, line) s e -> withTCState (const s) $ do
+    TypeError (AgdaSourceErrorLocation file line) s e -> withTCState (const s) $ do
       reportSLn "error" 2 $ "Error raised in file " ++ file ++ " at line " ++ show line
```
Comment (andreasabel) [inline src/full/Agda/TypeChecking/Errors.hs]: (here)

File: src/full/Agda/TypeChecking/Pretty/Warning.hs [hunk 8]
```diff
@@ -38,7 +38,7 @@ import Agda.Utils.Pretty ( Pretty, prettyShow )
 import qualified Agda.Utils.Pretty as P
 
 instance PrettyTCM TCWarning where
-  prettyTCM w@(TCWarning (file, line) _ _ _ _) = do
+  prettyTCM w@(TCWarning (AgdaSourceErrorLocation file line) _ _ _ _) = do
     reportSLn "warning" 2 $ "Warning raised in file " ++ file ++ " at line " ++ show line
```
Comment (andreasabel) [inline src/full/Agda/TypeChecking/Pretty/Warning.hs]: (here)

**Review by andreasabel — CHANGES_REQUESTED** [review]
Thanks!

Driving my point further, I request a `Pretty` instance...

File: src/full/Agda/TypeChecking/Constraints.hs [hunk 9]
```diff
@@ -130,8 +130,9 @@ noConstraints problem = do
   (pid, x) <- newProblem problem
   cs <- getConstraintsForProblem pid
   unless (null cs) $ do
-    w <- warning_ (UnsolvedConstraints cs)
-    typeError $ NonFatalErrors [ w ]
+    withFileAndLine $ \ file line -> do
+      w <- warning'_ (file, line) (UnsolvedConstraints cs)
```
Comment (andreasabel) [inline src/full/Agda/TypeChecking/Constraints.hs]: Seems these two were forgotten...

**Review by andreasabel — CHANGES_REQUESTED** [review]

File: src/full/Agda/TypeChecking/Constraints.hs (hunk 9 above)
Comment (gallais) [reply src/full/Agda/TypeChecking/Constraints.hs]: I would have sworn that `make type-check` went through but clearly that is
not the case. :disappointed:

**Comment by WolframKahl** [comment]
> Please introduce a data type for the AgdaSourceErrorLocation (rather than using a pair). E.g.
> ```haskell
> data AgdaSourceErrorLocation = AgdaSourceErrorLocation
>   { slocFile :: String  -- ^ File of the Agda source code.
>   , slocLine :: Int     -- ^ Line number in this file
>   }
> ```

And probably use `FilePath` instead of `String`.

**Review by andreasabel — APPROVED** [review]
