### PR TITLE
Fix #7382: make all module param sections live in DeadCode

### LINKED ISSUE #7382: Agda 2.7.0-rc1 crashes when run twice, probably serialization issue
With the test case from #7380:
```agda
open import Agda.Builtin.IO
open import Agda.Builtin.Unit
open import Agda.Builtin.Nat
open import Agda.Builtin.Sigma

record R : Set where
  field x : Nat

variable r : R

data D : R → Nat → Set where
  c : let open R r in D r x

f : R → Nat
f x = fst g
  where
    g : Σ Nat (D x)
    g = (_ , c)

postulate print : Nat → IO ⊤
{-# COMPILE GHC print = print #-}

main = print (f (record { x = 3 }))
```
I get a crash if I run 2.7.0-rc1 twice on this file:
```
$ agda-2.7.0-rc1 Issue7380.agda && agda-2.7.0-rc1 -c Issue7380.agda
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE_VERBOSE__, called at src/full/Agda/TypeChecking/Reduce.hs:224:18
```
https://github.com/agda/agda/blob/ea00db09917de741fb5cb491639391f7af121369/src/full/Agda/TypeChecking/Reduce.hs#L224-L225
The internal error goes away with `--no-save-metas`.
Also, it cannot be triggered in 2.6.4.3 with `--save-metas`, so it must be a fresh regression in the `--save-metas` feature.

### PR DESCRIPTION
**Pull request by AndrasKovacs**
Because currently all sections are stored in interfaces.

### CODE REVIEW

File: src/full/Agda/TypeChecking/DeadCode.hs [hunk 1]
```diff
@@ -67,9 +66,7 @@ eliminateDeadCode !scope = Bench.billTo [Bench.DeadCode] $ do
   let !rootExtraDefs = mapMaybe extraRootsFilter $ HMap.toList defs
   let !rootRewrites  = sig ^. sigRewriteRules
 
-  -- Andreas, Oskar, 2023-10-19, issue #6931:
-  -- Needed to avoid deleting parameter sections of empty modules.
-  let !rootModSections = (sig ^. sigSections) `Map.intersection` pubModules
+  let !rootModSections = sig ^. sigSections
```
Comment (andreasabel) [inline src/full/Agda/TypeChecking/DeadCode.hs:69]: @AndrasKovacs : Would be good to add a reference to issue #7382 in the code, for future reference and code comprehension.

Also please keep the reference to #6931 in.

**Comment by andreasabel** [comment]
Thanks for the fix!

File: src/full/Agda/TypeChecking/DeadCode.hs (hunk 1 above)
Comment (AndrasKovacs) [reply src/full/Agda/TypeChecking/DeadCode.hs:69]: Uhh, sorry for the hasty merge.

I deleted the old comment intentionally because it would be confusing for new code reviewers and it's not relevant now. The empty modules are a red herring, the previous implementation could generate ill-formed interfaces all the same, it's just that we haven't run into errors because of it.

Comment (andreasabel) [reply src/full/Agda/TypeChecking/DeadCode.hs:69]: I think referencing these two issues is still information a future developer can use to get more information about the topic.

**Comment by andreasabel** [comment]
The fix misses a regression test.

I am adding one in
- #7386
