### PR TITLE
remove copy trimming

### LINKED ISSUE #8134: Caching is broken
Consider the following two files:
* `M1.agda`:
  ```agda
  {-# OPTIONS -vtc.decl:5 #-}

  module M1 (M : Set) where

  open import M2 M

  Should-not-be-rechecked : Set₁
  Should-not-be-rechecked = Set

  F : A → Set₁
  F _ = Set
  ```
* `M2.agda`:
  ```agda
  module M2 (M : Set) where

  A : Set₁
  A = Set
  ```

When I load `M1.agda`, remove the definition of `F`, and reload, then `Should-not-be-rechecked` is rechecked. If I then restore `F` and reload, then `Should-not-be-rechecked` is rechecked again.

This is a regression, Agda 2.8.0 does not exhibit the same behaviour. Bisection points towards 05f0577938750c560b712e1d2e0eee82ce9743de ("Only generate copies for used names"), which adds `IORef`s to the abstract syntax. A later commit seems to have been intended to address problems with caching (b95a2ca4de00f5a7c35b7edc4e0183970b68f999, "fixup: caching with copy trimming"), but that commit does not fix this bug.

The following script could perhaps be the starting point of an interaction test suite test case, if interaction tests use a binary compiled with `-fdebug`:
```haskell
{-# LANGUAGE RecordWildCards #-}

import Control.Exception
import Data.List
import System.Directory
import System.Exit

import RunAgda

m1Short =
  unlines
    [ "{-# OPTIONS -vtc.decl:5 #-}"
    , "module M1 (M : Set) where"
    , "open import M2 M"
    , "Should-not-be-rechecked : Set₁"
    , "Should-not-be-rechecked = Set"
    ]

m1Long =
  m1Short ++
  unlines
    [ "F : A → Set₁"
    , "F _ = Set"
    ]

m2 =
  unlines
    [ "module M2 (M : Set) where"
    , "A : Set₁"
    , "A = Set"
    ]

main :: IO ()
main =
  runAgda [ "--no-default-libraries"
          , "--ignore-interfaces"
          ] $ \(AgdaCommands { .. }) -> do

  echoUntilPrompt

  flip finally
    (-- Remove generated files before exiting the script.
     removeFile "M1.agda"  `finally`
     removeFile "M1.agdai" `finally`
     removeFile "M2.agda"  `finally`
     removeFile "M2.agdai") $ do

    -- Write M2.
    writeFile "M2.agda" m2

    -- Write and load M1.
    writeFile "M1.agda" m1Long
    loadAndEcho "M1.agda"

    -- Remove the last definition from M1 and type-check the file
    -- again.
    writeFile "M1.agda" m1Short
    ss1 <- loadAndEcho "M1.agda"

    -- Restore the last definition and type-check the file one more
    -- time.
    writeFile "M1.agda" m1Long
    ss2 <- loadAndEcho "M1.agda"

    -- The definition "Should-not-be-rechecked" should not be
    -- rechecked.
    if any ("Checking Should-not-be-rechecked" `isInfixOf`)
         (ss1 ++ ss2)
      then exitFailure
      else return ()
```

### LINKED ISSUE #8202: Regression related to caching
Consider the following modules:
* `M1.agda`:
  ```agda
  module M1 (_ : Set₁) where

  data D (_ : Set) : Set where
  ```
* `M2.agda`:
  ```agda
  module M2 where

  postulate A : Set
  ```
* `Bug.agda`:
  ```agda
  import M1

  module Bug
    (_ : Set)
    (open M1 Set)
    (_ : Set)
    where

  open import M2

  postulate _ : A

  _ : Set₁
  _ = ?
  ```

If I load `Bug`, replace the goal with `Set`, and reload, then the following internal error is triggered:
```
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at
src/full/Agda/TypeChecking/Monad/Context.hs:215:32 in
Agda-2.9.0-[…]:Agda.TypeChecking.Monad.Context
```
The error goes away if I restart Agda, and the error does not appear if caching is disabled. The example may look somewhat contrived, but I have encountered this bug rather frequently.

This is a regression. Bisection points towards b95a2ca4de00f5a7c35b7edc4e0183970b68f999 ("fixup: caching with copy trimming"). The following script (which tests slightly different code) was used together with `agda-bisect`:
```haskell
#!/usr/bin/env runhaskell

{-# LANGUAGE RecordWildCards #-}

import Control.Exception
import Control.Monad
import Data.List
import System.Directory
import System.Exit

import RunAgda

bugBase =
  unlines
    [ "open import M1"
    , "import M2"
    , "module Bug (_ : Set) (open M2 Set) (r : R) where"
    , "postulate _ : R.A r"
    , "_ : Set₁"
    ]

bug1 =
  bugBase ++
  unlines
    [ "_ = ?"
    ]

bug2 =
  bugBase ++
  unlines
    [ "_ = Set"
    ]

m1 =
  unlines
    [ "module M1 where"
    , "record R : Set₁ where"
    , "  field A : Set"
    ]

m2 =
  unlines
    [ "module M2 (_ : Set₁) where"
    , "data D (_ : Set) : Set where"
    ]

main :: IO ()
main =
  runAgda [ "--no-default-libraries"
          , "--ignore-interfaces"
          ] $ \(AgdaCommands { .. }) -> do

  echoUntilPrompt

  flip finally
    (-- Remove generated files before exiting the script.
     mapM_
       (\f -> do
         ex <- doesFileExist f
         when ex (removeFile f))
       [ "Bug.agda"
       , "Bug.agdai"
       , "M1.agda"
       , "M1.agdai"
       , "M2.agda"
       , "M2.agdai"
       ]) $ do

    -- Write Bug, M1 and M2.
    writeFile "Bug.agda" bug1
    writeFile "M1.agda" m1
    writeFile "M2.agda" m2

    -- Load Bug.
    loadAndEcho "Bug.agda"

    -- Complete the final definition in Bug and reload.
    writeFile "Bug.agda" bug2
    ss <- loadAndEcho "Bug.agda"

    -- No internal error should be raised.
    if any ("__IMPOSSIBLE__" `isInfixOf`) ss
      then exitFailure
      else return ()
```

### PR DESCRIPTION
**Pull request by plt-amy**
👍

### CODE REVIEW

**Comment by plt-amy** [comment]
👋

File: src/full/Agda/TypeChecking/Monad/Signature.hs [hunk 1]
```diff
@@ -541,17 +470,8 @@ applySection new ptel old ts info = do
...
           theDef <$> getConstInfo x <&> \case
-            Constructor{ conData = d }
-              -> Just (qnameModule y, d)
-
-            -- If we trimmed the record type away from a proper
-            -- projection we actually need to bring it back it otherwise
-            -- #1976 turns into #8037.
-            def | Just Projection{ projProper = Just r } <- isProjection_ def
-                , r `Map.member` del
-              -> Just (qnameModule y, r)
```
Comment (andreasabel) [inline src/full/Agda/TypeChecking/Monad/Signature.hs:552]: I am salvaging this hunk for the fix of #8037.
