### PR TITLE
Fix 8228: Parse Error with Display Pragma and Mixfix Operator

### LINKED ISSUE #8228: Parse Error with Display Pragma and Mixfix Operator
The below code produces a parse error:

```agda
postulate
  ℕ   : Set
  _+_ : ℕ → ℕ → ℕ
  foo : ℕ → ℕ

{-# DISPLAY foo (x + x) = x #-}
```

If we write `_+_ x y` or make `_+_` a constructor, the pragma is parsed correctly
```agda
postulate
  ℕ   : Set
  _+_ : ℕ → ℕ → ℕ
  foo : ℕ → ℕ

{-# DISPLAY foo (_+_ x x) = x #-}
```

```agda
data ℕ : Set where
  _+_ : ℕ → ℕ → ℕ

postulate
  foo : ℕ → ℕ

{-# DISPLAY foo (x + x) = x #-}
```

### PR DESCRIPTION
**Pull request by NathanielB123**
Fixes #8228: We stop pruning non-constructor operators from DISPLAY pragma patterns

### CODE REVIEW

File: src/full/Agda/Syntax/Concrete/Operators.hs [hunk 1]
```diff
@@ -108,11 +108,9 @@ data Parsers e = Parsers
     -- name parts occurs in the expression.
   }
 
-{-# SPECIALIZE
```
Comment (NathanielB123) [inline src/full/Agda/Syntax/Concrete/Operators.hs:111]: FYI, I tweaked the formatting here because this was breaking syntax highlighting (at least in VSCode) making the whole file very blue...

**Review by andreasabel — APPROVED** [review]
Thanks!

File: src/full/Agda/Syntax/Concrete/Operators.hs [hunk 2]
```diff
@@ -227,7 +225,7 @@ buildParsersFromOperatorScope kind top namesInExpr opScope = do
           _                                  -> __IMPOSSIBLE__
 
         -- If "or" is replaced by "and" in conParts/allParts below,
-        -- then the misspelled operator application "if x thenn x else
```
Comment (fredins) [inline src/full/Agda/Syntax/Concrete/Operators.hs:230]: I think "thenn" is supposed to be misspelled @NathanielB123

Comment (NathanielB123) [reply src/full/Agda/Syntax/Concrete/Operators.hs:230]: Oh oops
