### PR TITLE
Fix #7508: remove unused-arg optimization from the JS backend

### LINKED ISSUE #7508: Unused-arg optimization breaks function call
Agda `7b48a62` compiles this code

```agda
open import Agda.Builtin.Nat
open import Agda.Builtin.Bool

rng : Bool → Nat → Nat
rng _ _ = 4

flip : (Bool → Nat → Nat) → (Nat → Bool → Nat)
flip f a b = f b a

rng' : Nat → Bool → Nat
rng' = flip rng
```

to this JavaScript

```agda
var agdaRTS = require("agda-rts");

var z_jAgda_Agda_Builtin_Bool = require("jAgda.Agda.Builtin.Bool");
var z_jAgda_Agda_Builtin_Nat = require("jAgda.Agda.Builtin.Nat");
var z_jAgda_Agda_Primitive = require("jAgda.Agda.Primitive");

exports["flip"] = a => b => c => a(c)(b);
exports["rng"] = agdaRTS.primIntegerFromString("4");
exports["rng'"] = exports["flip"](exports["rng"]);
```

which is broken because `exports["flip"]` expects a function,
but is passed `exports["rng"]`, which Agda has optimized to a literal.

### PR DESCRIPTION
**Pull request by lawcho**
This PR removes unused-arg optimization from the JS backend, to fix #7508.

### CODE REVIEW

**Comment by andreasabel** [comment]
Converting this to draft because the test suite fails.  Please switch to "Ready for review" once it passes.

**Comment by andreasabel** [comment]
@caryoscelus @qlonik: grateful for a review.

File: src/full/Agda/Compiler/JS/Compiler.hs [hunk 1]
```diff
@@ -475,40 +462,72 @@ definition' kit q d t ls =
...
+--
+-- here is how "Foo" is compiled:
+--
+--  * A constructor definition, e.g.
+--
+--        c2 : X -> Y -> Foo
+--
+--    compiles to
+--
+--        exports["Foo"]["c2"] = x => y => k = k["c2"](x,y)
```
Comment (szumixie) [inline src/full/Agda/Compiler/JS/Compiler.hs]: The last `=` should be a `=>`.

File: src/full/Agda/Compiler/JS/Compiler.hs [hunk 2]
```diff
@@ -475,40 +462,72 @@ definition' kit q d t ls =
...
+--          (c2 x y) -> E2
+--          (c3 f  ) -> E3
+--
+--    compiles to
+--
+--        p(
+--          { "c1":           E1
+--          , "c2": x => y => E2
+--          , "c3": f      => E3
+--          })
```
Comment (szumixie) [inline src/full/Agda/Compiler/JS/Compiler.hs]: The object given to `p` contains uncurried functions in the compiled result:
```
p(
  { "c1": ()    => E1
  , "c2": (x,y) => E2
  , "c3": f     => E3
  })
```

Comment (szumixie) [reply src/full/Agda/Compiler/JS/Compiler.hs]: The `c1` case is also compiled to a function, with no arguments.

**Comment by lawcho** [comment]
Bugs #7531, #7532 occur in this branch, but also in `master`.
So I recommend merging this PR even without fixes for those bugs

**Comment by andreasabel** [comment]
The code up for deleting here originates from:
- https://github.com/agda/agda/pull/3395

Any chance the code could be fixed rather than removed?

Code author was @divipp "with contributions by" (quoting the commit) @phile314.
@asr assisted in merging the PR.

@divipp @phile314 Do you see a way to fix the unused argument optimization?

**Review by Deviselfira — APPROVED** [review]

**Comment by andreasabel** [comment]
PR redone in #8002 to include removal of unused local functions that became obsolete after removing the unused-arg optimization.
- #8002
