### PR TITLE
Boundary scavenging

### LINKED ISSUE #3605: Improve constraint reporting for cubical
This is surely well-known but I haven’t found a bug report about it. I find it quite difficult to work with cubical Agda because the constraint reporting on end points is incomprehensible. See for instance the code below.

```agda
{-# OPTIONS --cubical #-} 

open import Cubical.Core.Everything public

postulate
  A : Set
  a b a' b' : A
  p : a ≡ b

test : a' ≡ b'
test i = hcomp (λ j → (λ {(i = i0) → ?; (i = i1) → ?})) (p i)
```

Current output when doing `C-c C-l`:
```
?0 : A
?1 : A
_15 : A  [ at /tmp/xx.agda:11,10-68 ]
_16 : A  [ at /tmp/xx.agda:11,10-68 ]

———— Errors ————————————————————————————————————————————————
Failed to solve the following constraints:
  a' = _16 (i = i0) : A
  b' = _16 (i = i1) : A
  _15
    := λ i →
         hcomp (λ j → λ { (i = i0) → ?0 (j = j) ; (i = i1) → ?1 (j = j) })
         (p i)
    [blocked on problem 20]
  [20] b = ?1 (j = i0) : A
  [20] a = ?0 (j = i0) : A
```

Expected output:
```
?0 : A
?1 : A

———— Constraints ————————————————————————————————————————————————
?0 (j = i0) = a : A
?0 (j = i1) = a' : A
?1 (j = i0) = b : A
?1 (j = i1) = b' : A
```

In addition, there shouldn’t be any yellow in this file.

### LINKED ISSUE #3690: Cubical interaction: Display inferred type with interval variables instantiated
When working with Cubical Agda it might be nice if commands like `agda2-goal-and-context-and-inferred` (`C-c C-.`) included information about the value of the given expression for each relevant instantiation of interval variables.

### LINKED ISSUE #5900: De Bruijn fail in Cubical (Was: Garbled boundary contexts & naming eta expansion.)
The following minimal example does _not_ cause a problem:
```agda
{-# OPTIONS --cubical #-}

open import Agda.Builtin.Cubical.Path
open import Agda.Primitive.Cubical

record _×_ (A B : Set) : Set where
  constructor _,_
  field
    fst : A
    snd : B
open _×_

eta : ∀ {A B} (p q r : A × B) → p ≡ p
eta p q@(q1 , q2) r i = {!!}
```
so I will have to refer to my own code.

There are some holes at
* https://github.com/anuyts/ctx-alg/blob/15259093b0802315d7dc1d6b061540305680e1d7/src/Mat/Term.agda#L609
* https://github.com/anuyts/ctx-alg/blob/15259093b0802315d7dc1d6b061540305680e1d7/src/Mat/Term.agda#L623
* https://github.com/anuyts/ctx-alg/blob/15259093b0802315d7dc1d6b061540305680e1d7/src/Mat/Term.agda#L631

The latter 2 goals (and originally the first one) give me garbled boundary contexts in the output:
```
t = algebraHom t j, carrierHom₁ = i0 ⊢ ...
t = algebraHom t j, carrierHom₁ = i1 ⊢ ...
t = algebraHom t j, strHom₁ = i0 ⊢ ...
t = algebraHom t j, strHom₁ = i1 ⊢ ...
```
The appearance of the names `carrierHom₁` and `strHom₁`, which are the names of the constructors of `AlgebraHom` (with a `₁` appended), gave me the idea that this is a de Bruijn fail related to some but not all of the Algebra and AlgebraHom arguments being eta-expanded on the LHS in the code base. So for the first hole I changed the LHS from
```agda
ModelHom1Eq→IsTermAlgebraHom' m1EqA m1EqB@(algebra msetB β1 , respectsEqB) m1EqF sort (joinFQ-varF t j) i = ?
```
to
```agda
ModelHom1Eq→IsTermAlgebraHom'
  m1EqA@(algebra msetA α1 , respectsEqA)
  m1EqB@(algebra msetB β1 , respectsEqB)
  m1EqF@(algebraHom f f-isalg1) sort (joinFQ-varF t j) i = ?
```
and this actually solved the problem.

I am on Agda version 2.6.2-246a229.

Note: the linked repository contains a submodule and should be cloned with `git clone --recurse-submodules`.

### LINKED ISSUE #5997: Collect interaction point boundaries while elaborating right-hand-sides?
# Background

The user experience for Cubical Agda is subpar, and one of the biggest problems is that, even though interaction points _appear_ to have boundaries, there is a very limited set of circumstances that will actually cause an interaction point's boundary to be restricted. To wit: this only happens in `checkIApplyConfluence`, so if the interaction point does not have a boundary specified by the LHS of its clause, it will never have a boundary at all.

This poses some problems! For example, consider the following example:

```agda
double-comp
  : ∀ {ℓ} {A : Type ℓ} {w x y z : A} (p : w ≡ x) (q : x ≡ y) (r : y ≡ z)
  → w ≡ z
double-comp {ℓ = ℓ} {A = A} p q r i =
  hcomp {ℓ = ℓ} {A = A}
    (λ { j (i = i0) → {!   !} -- 0
       ; j (i = i1) → {!   !} -- 1
       })
      {! !}                   -- 2
```

Here, all the interaction points are "cubical", and thus have _some_ boundary (even though IP 2's boundary is fairly unspecified). But these boundaries are not fixed by the LHS, so the interaction points do not carry information about their boundary. Put concretely, the problems with the current interaction point boundary mechanism are as follows:

**Problem 1**: The boundary of an interaction point is usually _not_ fully determined simply by the LHS of the clause.

**Problem 2**: Interaction points in the same clause can have different boundaries.

**Problem 3**: The data which specifies an interaction point's boundary is underspecified for the purposes of computation.

# A proposal

1. The type of interaction point boundaries (`IPBoundary'`) should contain more specific information about what specific face is being described. Rather than carrying around a list of `(Term, Term)` equations (`ipbEquations`), each boundary condition should have a list of `(Var, Bool)` mappings specifying the _specific_ face. (I'll get to why we would want this refinement in a second). The rest of the type can stay as-is.

2. The list of `Closure IPBoundary` should not be attached to the clause. It should be attached directly to the `InteractionPoint`. This is a matter of both semantics and cleanliness: Semantically, the clause has nothing to do with the interaction points' boundary, as the `double-comp` example shows, and for cleanliness, this would keep the
invariant that `IPClause` is set only once by the coverage checker, and that _same_ `IPClause` is used by all the IPs in that clause.

3. Rather than collecting the boundary up-front, any suitable unification problem against an interaction point should refine its boundary. Concretely: In `Agda.TypeChecking.MetaVars.assign`, the `inverseSubst` function would have a new failure case: a refinement of `NeutralArg` for when the argument is one of the endpoints of the interval --- let's say it's `BoundaryArg`, but I'm not too concerned about the name. On this specific failure case, we would try to recover the unification problem as follows.

Let's use one of the unsolved constraints from `double-comp` as a representative example.

```
  z = ?1 (p = p) (q = q) (r = r) (j = i1) : A (blocked on _17)
```

`inverseSubst`, faced with these `Args`, would throw our new `BoundaryArg` exception, indicating the position of the first interval argument, which in this case is position `n = 3`. Then, we run the following checks:

- Taking the first _n_ arguments should give a list of `Args` in the pattern fragment, i.e., `inverseSubst` should _succeed_ for that `Args`. If this fails, we abort.

- Arguments in positions _n_ and up should consist only of applications to endpoints. I believe that the `Args` is guaranteed to be well-typed, but in case it is not, we can also enforce that dropping the first `n` binders from `telViewUpToPath (length args)` leaves us with `length args - n`-many interval-typed binders.

If both these checks succeed _and_ we are in one of the cubical modes _and_ the `MetaId` refers to an interaction point, then we are looking at a boundary, and _not_ an unsolved constraint. In that case I believe we can:

- Record the _n_-and-up'th arguments as making up the `Face`;
- Record the RHS of the equation as making up.. well, the right-hand-side of the boundary;
- Add this boundary constraint to the interaction point's data
- _Ignore the unification problem._ This is the part I'm iffiest about: I believe it'd be fine, since it would otherwise go unsolved after all, but perhaps it is more correct for it to be "blocked on boundary".

# Benefits

The biggest immediate benefit is that, assuming it is alright to drop the unification problem, cubical programs in the process of being written would have _a lot less_ type errors than they usually appear to have. Hopefully this would reduce the amount of yellow being shown to the user but I'm a bit less sure of that.

This refactoring means that `IPBoundary` now has a semantic meaning.  Specifically, we can look at an interaction point (say the same `?0` above) and construct a _precise_ cubical type specifying what terms would fit there. An interaction point in telescope `Γ` of type `T` with boundary conditions given by `φ₁ ⊢ t`, `φ₂ ⊢ s`, ..., is really `outS` of some term typable in the empty context as

```
Π Γ → Sub T (φ₁ ∨ φ₂ ∨ ...) λ { (φ₁ = i1) → t ; (φ₂ = i1) → s ; ... }
```

While it appears that this doesn't immediately translate to a benefit for the user, it _does_: If `⋁ φ` is logically equivalent to the disjunction `⋁ (i ∨ ~ i)` (`i` ranges over the variables mentioned in `φ`), then the `Sub` above is really an iterated `PathP`, _and we can tell the user that_! The interaction command which computes a helper function type can look for this special case and show the helper function type as a Path-type.

As an example, after specifying the base for `double-comp` (i.e. the user specifying that `?2 = q i`), we would be left with the following "type-and-boundaries" for the interaction points 0 and 1:

```
?0 :
  ∀ {l} {A : Type l} {w x y z : A} (p : w ≡ x) (q : x ≡ y) (r : y ≡ z)
  → (j : I) → Sub A (j ∨ ~ j) λ { (j = i0) → x ; (j = i1) → w }
?1 :
  ∀ {l} {A : Type l} {w x y z : A} (p : w ≡ x) (q : x ≡ y) (r : y ≡ z)
  → (j : I) → Sub A (j ∨ ~ j) λ { (j = i0) → y ; (j = i1) → z }
```

which, since `j ∨ ~ j` _is_ the disjunction of the boundary of `j`, could be displayed in simplified form as

```
?0 :
  ∀ {l} {A : Type l} {w x y z : A} (p : w ≡ x) (q : x ≡ y) (r : y ≡ z)
  → Path A x w
?1 :
  ∀ {l} {A : Type l} {w x y z : A} (p : w ≡ x) (q : x ≡ y) (r : y ≡ z)
  → Path A y z
```

### PR DESCRIPTION
**Pull request by plt-amy**
Third time's the charm?

Closes #5997, closes #5900, closes #3605, closes #3690. As proposed in #5997, boundary constraints are recovered during unification, before bailing in `assignMeta'`. If the meta assignment failed because the meta spine had endpoints (`i0`/`i1`) on it, we invert the spine anyway, but add the RHS as a boundary constraint. Inverting the meta spine is necessary to put all the RHS-es collected during unification in the same context: the top-level context. When printing, we apply the RHS-es (represented by lambdas) to the meta's context.

The boundary of an interaction point in context `Γ` is a `Map (IntMap Bool) Term`; the `Term` is guaranteed to be headed by (at least) as many lambdas as there are variables in `Γ`. Higher-order situations, eg. funext before introducing the point argument, can lead to extra lambdas. Each `IntMap Bool` has its `keysSet` a subset of the `I`-typed variables in `Γ`.

Since we store the face constraints as keyed by variables in the actual meta context (instead of in an arbitrary closure), it's trivial to implement #3690. I changed the boundary display to look like the following when running `Cmd_goal_type_context_infer` w/ a non-empty interaction point.

```
A
———— Boundary (wanted) —————————————————————————————————————
k = i0 ⊢ x
k = i1 ⊢ p j
j = i0 ⊢ ?2 (p = p) (q = q) (i = i0) (k = k)
j = i1 ⊢ ?3 (p = p) (q = q) (i = i0) (k = k)

A
———— Boundary (actual) —————————————————————————————————————
k = i0 ⊢ x
k = i1 ⊢ p j
j = i0 ⊢ x
j = i1 ⊢ p k
```

Demo from a week or so ago:

https://user-images.githubusercontent.com/29957583/224825096-691ef729-9e32-4e09-8bbe-8f9f1aa31d6e.mp4

----

Overview of changes:

- Added `isFaceConstraint`, `tryAddBoundary` to `MetaVars.hs`. These turn equational problems into boundary constraints (according to the scheme I proposed in #5997)
- `IPBoundary` is now a newtype of that `Map` type I mentioned, the user sees a list of `IPFace'` instead. `getIPBoundary` in `BasicOps.hs` is responsible for turning that boundary into a list of `IPFace'`s in the right context. Boundaries are associated with the IP instead of the IPClause.
- Unsolved constraints that satisfy `isFaceConstraint` are not reported as `UnsolvedConstraints` warnings, but as `InteractionMetaBoundaries` instead (`getAllUnsolvedWarnings` in `Pretty/Warnings.hs`)
- IApplyConfluence doesn't have to invent IPBoundaries anymore.

### CODE REVIEW

**Comment by plt-amy** [comment]
Twice today I got a CI failure on a nontrivial change because the left fish is not in scope... one would have thought I would have learned

File: src/full/Agda/Interaction/JSONTop.hs [hunk 1]
```diff
@@ -287,17 +287,17 @@ instance EncodeTCM Blocker where
 instance EncodeTCM DisplayInfo where
   encodeTCM (Info_CompilationOk backend wes) = kind "CompilationOk"
     [ "backend"           @= encodePretty backend
-    , "warnings"          #= encodeTCM (filterTCWarnings (tcWarnings wes))
-    , "errors"            #= encodeTCM (filterTCWarnings (nonFatalErrors wes))
+    , "warnings"          #= (encodeTCM $ filterTCWarnings (tcWarnings wes))
+    , "errors"            #= (encodeTCM $ filterTCWarnings (nonFatalErrors wes))
```
Comment (andreasabel) [inline src/full/Agda/Interaction/JSONTop.hs]: Haha, you are rewriting in the opposite direction of `hlint`.  This might clash with @philderbeast 's efforts in
- https://github.com/agda/agda/pull/6461

This is an observation only, I am not taking sides here.  Personally, I am not convinced that `hlint` is a productivity booster for this repo.

File: src/full/Agda/TypeChecking/Monad/Base.hs [hunk 2]
```diff
@@ -1640,12 +1640,13 @@ instance LensIsAbstract MetaInfo where
...
-  , ipMeta  :: Maybe MetaId -- ^ The meta variable, if any, holding the type etc.
-  , ipSolved:: Bool         -- ^ Has this interaction point already been solved?
-  , ipClause:: IPClause
+  { ipRange  :: Range        -- ^ The position of the interaction point.
+  , ipMeta   :: Maybe MetaId -- ^ The meta variable, if any, holding the type etc.
+  , ipSolved :: Bool         -- ^ Has this interaction point already been solved?
+  , ipClause :: IPClause
       -- ^ The clause of the interaction point (if any).
       --   Used for case splitting.
+  , ipBoundary :: IPBoundary
```
Comment (andreasabel) [inline src/full/Agda/TypeChecking/Monad/Base.hs:1649]: Since you added spaces before `::` in the other clauses, would you mind aligning all the clauses?

File: src/full/Agda/TypeChecking/Monad/Constraints.hs [hunk 3]
```diff
@@ -107,7 +109,7 @@ takeAwakeConstraint' p = do
 getAllConstraints :: ReadTCState m => m Constraints
 getAllConstraints = do
   s <- getTCState
-  return $ s^.stAwakeConstraints ++ s^.stSleepingConstraints
+  return $ s^.stAwakeConstraints ++ s ^. stSleepingConstraints
```
Comment (andreasabel) [inline src/full/Agda/TypeChecking/Monad/Constraints.hs]: Revert?  Or make uniform wrt. spacing the `^.` operator?

File: src/full/Agda/TypeChecking/Pretty/Constraint.hs [hunk 4]
```diff
@@ -37,18 +39,18 @@ prettyConstraint c = f (locallyTCState stInstantiateBlocking (const True) $ pret
...
-prettyInterestingConstraints cs = mapM (prettyConstraint . stripPids) $ List.sortBy (compare `on` isBlocked) cs'
-  where
-    isBlocked = not . null . allBlockingProblems . constraintUnblocker
+prettyInterestingConstraints cs = do
+  let
     cs' = filter interestingConstraint cs
+    isBlocked = not . null . allBlockingProblems . constraintUnblocker
     interestingPids = Set.unions $ map (allBlockingProblems . constraintUnblocker) cs'
     stripPids (PConstr pids unblock c) = PConstr (Set.intersection pids interestingPids) unblock c
+  mapM (prettyConstraint . stripPids) $ List.sortBy (compare `on` isBlocked) cs'
```
Comment (andreasabel) [inline src/full/Agda/TypeChecking/Pretty/Constraint.hs]: Just a stylistic change `where -> let` ?

File: src/full/Agda/TypeChecking/Pretty/Warning.hs [hunk 5]
```diff
@@ -440,7 +448,7 @@ filterTCWarnings = \case
   -- Andreas, 2019-09-10, issue #4065:
   -- If there are several warnings, remove the unsolved-constraints warning
   -- in case there are no interesting constraints to list.
-  ws  -> (`filter` ws) $ \ w -> case tcWarning w of
+  ws  -> flip filter ws $ \ w -> case tcWarning w of
```
Comment (andreasabel) [inline src/full/Agda/TypeChecking/Pretty/Warning.hs]: Stylistic change.

File: src/full/Agda/Interaction/JSONTop.hs [hunk 6]
```diff
@@ -287,17 +287,17 @@ instance EncodeTCM Blocker where
...
   encodeTCM (Info_Constraints constraints) = kind "Constraints"
     [ "constraints"       #= forM constraints encodeTCM
     ]
   encodeTCM (Info_AllGoalsWarnings (vis, invis) wes) = kind "AllGoalsWarnings"
     [ "visibleGoals"      #= forM vis (\i -> withInteractionId (B.outputFormId $ OutputForm noRange [] alwaysUnblock i) $ encodeOC encodeTCM encodePrettyTCM i)
     , "invisibleGoals"    #= forM invis (encodeOC encodeTCM encodePrettyTCM)
-    , "warnings"          #= encodeTCM (filterTCWarnings (tcWarnings wes))
-    , "errors"            #= encodeTCM (filterTCWarnings (nonFatalErrors wes))
+    , "warnings"          #= (encodeTCM $ filterTCWarnings (tcWarnings wes))
+    , "errors"            #= (encodeTCM $ filterTCWarnings (nonFatalErrors wes))
```
Comment (andreasabel) [inline src/full/Agda/Interaction/JSONTop.hs]: Ditto. (Stylistic change.)

**Review by andreasabel — APPROVED** [review]
Great! A PR with video demo! A new level of PR motivation!

I just skimmed the text, noticing a few stylistic changes.  If it is not too much effort, would you mind putting them into a separate commit, or for some, revert them maybe?  (Depending how strongly you feel about them.)

**Comment by plt-amy** [comment]
All but one of those changes were from _partially_ reverting an attempt to make `interestingConstraint` more accurate --- so I don't mind reverting them fully :slightly_smiling_face:

**Comment by andreasabel** [comment]
@plt-amy : Consider adding some advertisement to CHANGELOG.
