### PR TITLE
Fix #8218: Update signature for imported rewrite rules

### LINKED ISSUE #7893: Confluence check misses critical pair
Example code:
```agda

{-# OPTIONS --rewriting --local-confluence-check #-}

module ConfluenceBug where

open import Agda.Builtin.Equality
open import Agda.Builtin.Equality.Rewrite
open import Agda.Builtin.List
open import Agda.Builtin.Nat

private variable
  A : Set
  x : A
  m n : Nat

_++_ : List A → List A → List A
[] ++ ys = ys
(x ∷ xs) ++ ys = x ∷ (xs ++ ys)

replicate : Nat → A → List A
replicate zero x = []
replicate (suc n) x = x ∷ replicate n x

postulate
  replicate-rew : replicate (m + n) x ≡ replicate m x ++ replicate n x
  plus-zero : m + 0 ≡ m

{-# REWRITE replicate-rew #-}
{-# REWRITE plus-zero #-}
```
The confluence checker does not report any errors, but it does when the order of the rewrite rules is swapped.

### LINKED ISSUE #8218: Unequal terms despite rewrite rule (across modules)
Minimal reproducer:

```agda
{-# OPTIONS --rewriting #-}
open import Data.List using (List ; [] ; _∷_ ; map)

postulate _++_ : ∀{A : Set} → List A → List A → List A

open import Agda.Builtin.Equality
open import Agda.Builtin.Equality.Rewrite

postulate map-++ : ∀ {A B : Set} (f : A → B) xs ys → map f (xs ++ ys) ≡ map f xs ++ map f ys
{-# REWRITE map-++ #-}

data Ty : Set where
  _⟶_ : List Ty → Ty → Ty

data Exp (Γ : List Ty) : Ty → Set where
  lamMany : ∀{τ} (τs : List Ty) → Exp (τs ++ Γ) τ → Exp Γ (τs ⟶ τ) 

{-# TERMINATING #-}
desugarTy : Ty → Ty
desugarTy (τs ⟶ τ) = map desugarTy τs ⟶ desugarTy τ

desugarExp : ∀{Γ τ} → Exp Γ τ → Exp (map desugarTy Γ) (desugarTy τ)
desugarExp (lamMany τs x) = lamMany (map desugarTy τs) {!desugarExp x!}
```

If I ask for the normalized type of the hole I get:

```
Goal: Exp (map desugarTy τs ++ map desugarTy Γ) (desugarTy τ)
Have: Exp (map desugarTy τs ++ map desugarTy Γ) (desugarTy τ)
```

But when I give `desugarExp x` I get this error:

```
error: [UnequalTerms]
(map desugarTy _Γ_67) !=< (map desugarTy τs ++ map desugarTy Γ) of
type (List Ty)
when checking that the inferred type of an application
  Exp (map desugarTy _Γ_67) (desugarTy _τ_68)
matches the expected type
  Exp (map desugarTy τs ++ map desugarTy Γ) (desugarTy τ)
```

Interestingly, the issue disappears if I move the definition of `map` from `Data.List` to this file.

Agda version: 2.8.0
Stdlib version: 2.1.1

### PR DESCRIPTION
**Pull request by NathanielB123**
Fix #8218: to correctly handle rewrite rules declared in modules downstream from the definitions they modify (e.g. their head symbol), we need to update the imported signature.

### CODE REVIEW

File: src/full/Agda/TypeChecking/Monad/State.hs [hunk 1]
```diff
@@ -253,19 +261,23 @@ withSignature sig m = do
...
-  . (setMatchableSymbols f matchables)
-    where
-      setNotInjective def@Function{} = def { funInv = NotInjective }
-      setNotInjective def            = def
+addRewriteRulesFor :: QName -> RewriteRules -> Signature -> Signature
+addRewriteRulesFor f rews =
+  over sigRewriteRules $ HMap.insertWith mappend f rews
+
+updateSignatureForRewrites :: QName -> RewriteRules -> [QName]
+                           -> Signature -> Signature
```
Comment (andreasabel) [inline src/full/Agda/TypeChecking/Monad/State.hs]: The preferred style for function signatures is:
```haskell
updateSignatureForRewrites :: 
     QName 
       -- ^ ...
  -> RewriteRules 
       -- ^ ...
  -> [QName]
       -- ^ ...
  -> Signature 
       -- ^ ...
  -> Signature
       -- ^ ...
```
This includes documentation of each argument.  
This might seem silly at some times, when the purpose of an argument is pretty clear, but I think it is better to include "obivous" documentation than to leave out documentation.
In this case for instance, it is not obvious to me what `[QName]` are without also reading the code.

So if you have found out the purpose of the arguments in your efforts to understand the code, it would be nice to leave these insights as documentation there.
(I am aware that much of the code base does not give a good example when it comes to documentation, but I want to change this.)

File: src/full/Agda/Interaction/Imports.hs [hunk 2]
```diff
@@ -379,6 +371,25 @@ addImportedThings isig metas ibuiltin patsyns display userwarn
   stOpaqueBlocks         `modifyTCLens` \ imp -> imp `Map.union` oblock
   stOpaqueIds            `modifyTCLens` \ imp -> imp `Map.union` oid
 
+-- | Merges two signatures, assuming the second is being imported into the first
+--
+-- This is not commutative, because we assume rewrite rules in the second
+-- signature cannot refer to definitions in the first.
```
Comment (andreasabel) [inline src/full/Agda/Interaction/Imports.hs]: Maybe the comment could say something about the bias.  `Map.union` is left-biased so `importSignature` inherits this bias.
So, yes, it is not commutative.

I am surprised about the "cannot":  If I import both A and B and B also imports A, can't rewrite rules in B refer to symbols in A (which are then already in my imported signature)?

**Review by andreasabel — COMMENTED** [review]
Thanks for chasing down the issue and fixing it!

File: src/full/Agda/Interaction/Imports.hs (hunk 2 above)
Comment (NathanielB123) [reply src/full/Agda/Interaction/Imports.hs]: Ah yes, good point, I didn't think about that case. I think the code is correct but justification I had for this was wrong.

Comment (NathanielB123) [reply src/full/Agda/Interaction/Imports.hs]: Fixed comment

File: src/full/Agda/TypeChecking/Monad/State.hs (hunk 1 above)
Comment (NathanielB123) [reply src/full/Agda/TypeChecking/Monad/State.hs]: That makes sense. I have now documented the type signatures of all the new functions from this PR

**Review by andreasabel — APPROVED** [review]
Excellent!

**Comment by andreasabel** [comment]
Rebase or squash?  You can add one of the labels `pr: squash` or `pr: preserve commits` to indicate the preferred way of merging this.
When merging individual commits, each must build correctly.

**Comment by NathanielB123** [comment]
> Rebase or squash?

I don't mind - I think each commit here should build, but some are quite boring/I'm not sure much is gained from keeping them separate. Regardless, I can't seem to add labels though (I guess I don't have permissions?)

**Review by jespercockx — APPROVED** [review]
