### PR TITLE
Changes related to issues #4927, #6238, #6263, #6264 and #6265

### LINKED ISSUE #4927: should flat be off by default?
it is strange to me that flat is on by default. I always think of Agda's type system as something around MLTT but the flat modality itself seems kicking it off the range. I am wondering why flat is on by default? I would expect a special option to turn it on as it is an addon feature.

### LINKED ISSUE #6263: Error related to `--flat-split` when this option is not used
Some of my code triggered the following error:
```
Importing module […] using the --flat-split flag
from a module which does not.
```
The code does not mention the `--flat-split` flag. I think the error is triggered because the importing module uses `--cubical-compatible` and `--with-K`, whereas the imported module uses `--with-K` and not `--cubical-compatible`.

I see three ways to fix this problem:
* I could use `--no-flat-split`.
* We could turn off `--flat-split` by default also when `--with-K` is used. This is my preferred choice, even though this could break some code.
* We could turn on `--flat-split` when both `--with-K` and `--cubical-compatible` are used.

### LINKED ISSUE #6264: Unused options
The following options seem to be unused, and could presumably be removed:
* https://github.com/agda/agda/blob/7588018496fbf489668bceb4ca99f401711053a2/src/full/Agda/Interaction/Options/Base.hs#L127
* https://github.com/agda/agda/blob/7588018496fbf489668bceb4ca99f401711053a2/src/full/Agda/Interaction/Options/Base.hs#L161

### LINKED ISSUE #6265: Some options should be listed in `restartOptions`
The following options are not listed in `restartOptions`:
* `optCopatterns`
* `optFirstOrder`
* `optFlatSplit`
* `optForcing`
* `optKeepCoveringClauses`
* `optPatternMatching`
* `optProjectionLike`

The following options related to backends are also not included, but perhaps that is fine, if the idea is that the backends should take care of recompilation logic:
* `optCompileNoMain`
* `optCountClusters`

Perhaps the following options related to performance could be removed from the list:
* `optCallByName`
* `optFastReduce`
* `optSaveMetas`

It is apparently easy to forget to add a new option to `restartOptions`. Perhaps we could instead use a function that blanks out options that should not trigger a "restart".

### PR DESCRIPTION
**Pull request by nad**

### CODE REVIEW

File: src/full/Agda/Interaction/Options/Base.hs [hunk 1]
```diff
@@ -409,62 +406,30 @@ unsafePragmaOptions clo opts =
...
-  , (B . optEraseRecordParameters, "--erase-record-parameters")
-  , (B . not . optLoadPrimitives, "--no-load-primitives")
-  ]
+-- | This function returns 'True' if the file should be rechecked.
 
--- to make all restart options have the same type
-data RestartCodomain
-  = C CutOff | B Bool | I Int | M !(Strict.Maybe Int) | W WarningMode
-  deriving Eq
+recheckBecausePragmaOptionsChanged
```
Comment (andreasabel) [inline src/full/Agda/Interaction/Options/Base.hs:414]: Makes sense to whitelist rather than black-listing options (so the default is "recheck").
The documentation has a blacklist, so should that be updated?
https://github.com/agda/agda/blob/7588018496fbf489668bceb4ca99f401711053a2/doc/user-manual/tools/command-line-options.rst?plain=1#L1090-L1102
I also wondered how we ensure the doc is in sync with the code here...

Comment (nad) [reply src/full/Agda/Interaction/Options/Base.hs:414]: Does anyone rely on that list in the documentation? Perhaps it could be removed.

**Comment by nad** [comment]
I added the flag `--cohesion` (see #4927). The implementation is a little messy: the different parsers return information about every encountered occurrence of `@flat`/`@♭`, and it is up to the callers to check if these occurrences are OK after the pragma options have been set. I tried to perform this check in `ConcreteToAbstract`, but there does not seem to be a single piece of code that translates every occurrence of `Arg` or `ArgInfo`. One could perhaps add a check for every piece of concrete syntax that might contain this modality, but that is error-prone and could easily break in the future.

File: src/full/Agda/Syntax/Parser/Parser.y [hunk 2]
```diff
@@ -2403,8 +2404,15 @@ instance SetRange Attr where
...
 -- | Parse an attribute.
 toAttribute :: Expr -> Parser Attr
-toAttribute x = maybe failure (return . Attr (getRange x) y) $ exprToAttribute x
+toAttribute x = do
+  attr <- maybe failure (return . Attr r y) $ exprToAttribute x
+  case theAttr attr of
+    CohesionAttribute{} ->
+      modify' (\s -> s { parseCohesion = (y, r) : parseCohesion s })
+    _                   -> return ()
+  return attr
```
Comment (plt-amy) [inline src/full/Agda/Syntax/Parser/Parser.y:2413]: I wonder if we shouldn't make note of _every_ `Attr` we come across? If we ever implement, e.g., #6246, this would be the place to do it.

**Review by plt-amy — APPROVED** [review]
I think doing this check right out of the parser is a bit ugly, but I don't see another realistic way out. Disabling `@♭` by default is fine by me.

File: src/full/Agda/Syntax/Parser/Parser.y (hunk 2 above)
Comment (nad) [reply src/full/Agda/Syntax/Parser/Parser.y:2413]: That does not need to be done now.

File: src/full/Agda/Interaction/Options/Base.hs (hunk 1 above)
Comment (andreasabel) [reply src/full/Agda/Interaction/Options/Base.hs:414]: Could be turned into a `--help` topic instead.

Comment (nad) [reply src/full/Agda/Interaction/Options/Base.hs:414]: I don't plan to do anything about this before the release. Feel free to open a new issue for your suggestions.
