### PR TITLE
Fix #7529: treat `LevelUniv` in Cubical Agda

### LINKED ISSUE #7529: Strange problem with --level-universe and --cubical
The following code does not work:

```agda
{-# OPTIONS --cubical --level-universe #-}

open import Agda.Primitive

data _≡_ {l : Level} {X : Set l} : X → X → Set l where
  refl : {x : X} → x ≡ x

Jbased : {l : Level} {X : Set l} (x : X) (A : (y : X) → x ≡ y → Set l)
       → A x refl → (y : X) (r : x ≡ y) → A y r
Jbased x A b _ refl = b
```

and the error message is:
```
Panic: Pattern match failure in 'do' block at
src/full/Agda/TypeChecking/Rules/LHS/Unify/LeftInverse.hs:203:3-15
when checking that the pattern refl has type x ≡ y
```

If I remove either `--level-universe` or `--cubical` it works. Interestingly, changing the equality type to the builtin equality type makes it work:

```agda
{-# OPTIONS --cubical --level-universe #-}

open import Agda.Primitive
open import Agda.Builtin.Equality

Jbased : {l : Level} {X : Set l} (x : X) (A : (y : X) → x ≡ y → Set l)
       → A x refl → (y : X) (r : x ≡ y) → A y r
Jbased x A b _ refl = b
```

Me and @martinescardo came across this when trying to combine the TypeTopology and agda/cubical libraries.

### LINKED ISSUE #7535: Regression in 2.6.4: Agda thinks large propositions can be transported
The failing test for #6060 succeeds if we change `Prop` for `Propω`:
```agda
{-# OPTIONS --cubical --prop -WnoUnsupportedIndexedMatch #-}

open import Agda.Primitive
open import Agda.Builtin.Equality

data S : Set where s : S
data P : Propω where p : P

-- The following is rejected for P : Prop
-- so should also be rejected for P : Propω.

g : (x : S) → s ≡ x → P → S
g .s refl y = s
``` 
`Propω` was added in 2.6.4, but apparently not correctly in its interaction with `Cubical Agda`.

### PR DESCRIPTION
**Pull request by andreasabel**
Issue #7529 demonstrates that `--level-universe` is not (fully) integrated with `--cubical` (yet).

In this PR, I expand some catch-alls for sorts to fill in some speculative values for the new sort `LevelUniv`.
I need some experts to look over this: @arthur-adjedj @plt-amy @mortberg @Saizan @sattlerc 

One should probably check the Cubical Agda code for more such matches on sorts, e.g. grep for `Type l` or `getSort`.

Related are also:
- #7413 
- #7417

Commits:
- **Debug #7529**
- **Fix #7529 by speculating values for LevelUniv in Cubical Agda fibrancy**

### CODE REVIEW

File: src/full/Agda/TypeChecking/Primitive/Cubical.hs [hunk 1]
```diff
@@ -272,7 +272,17 @@ doPiKanOp cmd t ab = do
             Def q [] | Just q == mInterval -> return $ Just $ \_ _ a0 -> a0
             _ -> return Nothing
 
-        _ -> return Nothing
+        Prop _     -> pure Nothing
+        SSet _     -> pure Nothing
+        Inf _ _    -> pure Nothing
+        LevelUniv  -> pure Nothing
```
Comment (andreasabel) [inline src/full/Agda/TypeChecking/Primitive/Cubical.hs:278]: correct?

File: src/full/Agda/TypeChecking/Primitive/Cubical.hs [hunk 2]
```diff
@@ -950,19 +960,25 @@ transpSysTel' flag delta us phi args = do
...
-          Inf _ _  -> noTranspSort
-          SSet _  -> noTranspSort
-          SizeUniv -> noTranspSort
-          LockUniv -> noTranspSort
+          Univ _ _     -> noTranspSort
+          Inf _ _      -> noTranspSort
           IntervalUniv -> noTranspSort
-          Prop{}  -> noTranspSort
-          _ -> noTranspError b'
+          LevelUniv    -> noTranspSort
```
Comment (andreasabel) [inline src/full/Agda/TypeChecking/Primitive/Cubical.hs:972]: correct?

File: src/full/Agda/TypeChecking/Primitive/Cubical.hs [hunk 3]
```diff
@@ -973,15 +989,22 @@ transpSysTel' flag delta us phi args = do
...
-               LockUniv     -> return Nothing
-               Inf _ _ -> return Nothing
-               Type l -> Just <$> open (lam_i (Level l))
-               _ -> noTranspError (Abs "i" (unDom t))
-        t <- open $ Abs "i" (unDom t)
+          Univ UType l -> Just <$> open (lam_i (Level l))
+          Univ _ _     -> pure Nothing
+          Inf _ _      -> pure Nothing
+          IntervalUniv -> pure Nothing
+          LevelUniv    -> pure Nothing
```
Comment (andreasabel) [inline src/full/Agda/TypeChecking/Primitive/Cubical.hs:1001]: correct?

File: src/full/Agda/TypeChecking/Primitive/Cubical.hs [hunk 4]
```diff
@@ -1256,12 +1279,24 @@ toCType ty = do
...
+    SSet _ -> do
       t <- reduce (unEl ty)
       case t of
         Def q [] -> return $ Just $ ClosedType sort q
         _        -> return $ Nothing
-    _      -> return $ Nothing
+    Prop _       -> pure Nothing
+    Inf _ _      -> pure Nothing
+    IntervalUniv -> pure Nothing  -- ClosedType?  (See comment on CType.)
+    LevelUniv    -> pure Nothing  -- TODO: Or some ClosedType?
```
Comment (andreasabel) [inline src/full/Agda/TypeChecking/Primitive/Cubical.hs:1293]: correct?

**Comment by arthur-adjedj** [comment]
I have not dived into the issue, but from what I remember, there already were [some known issues](https://github.com/agda/agda/pull/6505#discussion_r1126784433) with regards to mixing `--level-universe` and `--cubical`. In particular, [`Cubical.agda`](https://github.com/agda/agda/blob/a4c522d46596c803315c062847487cc0af159d6c/src/data/lib/prim/Agda/Primitive/Cubical.agda) does not use `--level-universe`. According to @plt-amy [at the time](https://github.com/agda/agda/pull/6505#discussion_r1126813150), adding the `(IUniv, LevelUniv, LevelUniv)` PTS rule should not be problematic. If a full compatibility between the two pragmas is desirable, adding the rule and making it so that `cubical.agda` does compile with  `--level-universe` might be worth looking into.

File: src/full/Agda/TypeChecking/Primitive/Cubical.hs [hunk 5]
```diff
@@ -973,15 +989,22 @@ transpSysTel' flag delta us phi args = do
...
-               SSet _ -> return Nothing
-               IntervalUniv -> return Nothing
-               SizeUniv     -> return Nothing
-               LockUniv     -> return Nothing
-               Inf _ _ -> return Nothing
-               Type l -> Just <$> open (lam_i (Level l))
-               _ -> noTranspError (Abs "i" (unDom t))
-        t <- open $ Abs "i" (unDom t)
+          Univ UType l -> Just <$> open (lam_i (Level l))
+          Univ _ _     -> pure Nothing
```
Comment (andreasabel) [inline src/full/Agda/TypeChecking/Primitive/Cubical.hs]: This change of the behavior for `Prop` (from exception to `Nothing`) makes the failing test for #6060 pass.
However the test passes when we have `Propω` instead of `Prop`, see #7535.

Shouldn't `Prop` be treated like `SSet` here?  If not, why not?
I think this case distinction deserves a comment on what the intended behavior is on a higher level, in particular, when to return `Nothing` and when to throw an exception.
It also feels this should not be an adhoc pattern matching, but a function to be called with a proper documentation.  There are similar matches allover the Cubical Agda code base.

File: src/full/Agda/TypeChecking/Primitive/Cubical.hs (hunk 1 above)
Comment (Saizan) [reply src/full/Agda/TypeChecking/Primitive/Cubical.hs:278]: Yes, this matches `isCoFibrantSort`, we only return `Just` here for the `True` cases there: that's when a pi type should support kan operations.

File: src/full/Agda/TypeChecking/Primitive/Cubical.hs (hunk 2 above)
Comment (Saizan) [reply src/full/Agda/TypeChecking/Primitive/Cubical.hs:972]: As much as the rest, yes.

File: src/full/Agda/TypeChecking/Primitive/Cubical.hs (hunk 5 above)
Comment (andreasabel) [reply src/full/Agda/TypeChecking/Primitive/Cubical.hs]: I am now distinguishing `UProp` for both `Univ` and `Inf`, erroring out rather than returning `Nothing`.
This fixes the regressions for #6060 and #7535.

File: src/full/Agda/TypeChecking/Primitive/Cubical.hs (hunk 4 above)
Comment (Saizan) [reply src/full/Agda/TypeChecking/Primitive/Cubical.hs:1293]: Oh, actually `IntervalUniv` should have the check that's at `SSet` atm. I suppose that got overlooked when `IntervalUniv` got introduced. OTOH it seems then that the whole `ClosedType` thing might not actually be needed then.

I think it was meant to support path constructors for HITs, but those needed special care anyway?

Comment (andreasabel) [reply src/full/Agda/TypeChecking/Primitive/Cubical.hs:1293]: I raised this as #7542.

File: src/full/Agda/TypeChecking/Primitive/Cubical.hs (hunk 1 above)
Comment (nad) [reply src/full/Agda/TypeChecking/Primitive/Cubical.hs:278]: Perhaps it would make sense to tie this code more closely to `isCofibrantSort` (or at least to add some documentation of the connection).
