### PR TITLE
Generalize data and record params

### LINKED ISSUE #555: Wrong number of parameters given in datatype definitions
If you load Bug2.agda:
```agda
  module Bug2 where
  data Exp : Set
  data Exp Γ where 
```
You get
```
  An internal error has occurred. Please report this as a bug.
  Location of the error: src/full/Agda/TypeChecking/Rules/Data.hs:228
```
Obviously there's actually a problem with this file: the third line should be "data Exp where" not "data Exp Γ where", but the error message isn't helpful. 

> What version of Agda are you using? On what operating system (if relevant)?

I am on Mac OSX Snow Leopard, Agda 2.3.0, GHC 7.0.3.

Original issue reported on code.google.com by `robsimm...@gmail.com` on 12 Jan 2012 at 8:19

### LINKED ISSUE #952: Parse named implicit pi {x = y : A} -> B
Here is another issue with printing hidden function types (see also issue #951):
```agda
postulate
  f : {A : Set₁} → A → A

module _ (A : Set) where

  test : Set → Set
  test = f {A₁ = Set}

-- Bad printing of hidden function type in error:

-- Function does not accept argument {A₁ = _}
-- when checking that {A₁ = Set} are valid arguments to a function of
-- type {A₁ : Set₁} → A₁ → A₁
```
Names of hidden arguments are not subject to alpha-equality!

Thus, when we put `(A :  Set)` into the context, we cannot print the type of `f` as `{A₁ : Set₁} → A₁ → A₁`, because that suggests that the argument it expects has name `A₁`.

We rather have to choose a different name for the variable `A` bound in context, in case it should be printed as well.

Original issue reported on code.google.com by `andreas....@gmail.com` on 11 Nov 2013 at 10:03

### LINKED ISSUE #3296: Generalise in datatype and record parameters
Needs to generalise both the parameter telescope and the sort.

### PR DESCRIPTION
**Pull request by UlfNorell**
This fixes #3296, and in the process I also had to
- fix #555 properly
- change how parameters are bound in data/record defs (without sig) (see #1886 and #3323)
- fix parsing of named arguments in lambda/pi/telescope bindings (half-fixes #952)

There also snuck in a minor correction to my workaround for MacOS/xelatex problems (#3372), which I should have put directly on master, but meh.

Todo
- [x] Changelog and user manual
- [x] Finish fixing #952 (parsing works, but label is discarded during type checking)

### CODE REVIEW

File: src/full/Agda/Syntax/Concrete/Definitions.hs [hunk 1]
```diff
@@ -941,42 +894,68 @@ niceDeclarations fixs ds = do
...
+              <*> return ds
+
+        Data r Inductive x tel t cs -> do
+          pc <- use positivityCheckPragma
+          -- Andreas, 2018-10-27, issue #3327
+          -- Propagate {-# NO_UNIVERSE_CHECK #-} pragma from signature to definition.
+          -- Universe check is performed if both the current value of
+          -- 'universeCheckPragma' AND the one from the signature say so.
+          uc <- use universeCheckPragma
+          uc <- if uc == NoUniverseCheck then return uc else getUniverseCheckFromSig x
```
Comment (andreasabel) [inline src/full/Agda/Syntax/Concrete/Definitions.hs:913]: This line (and my comment on issue #3327) is only relevant for `DataDef` not for `Data` and should not have been copied here.

File: src/full/Agda/Syntax/Concrete/Definitions.hs [hunk 2]
```diff
@@ -941,42 +894,68 @@ niceDeclarations fixs ds = do
...
 
-        (Record r x i e c tel mt cs)   -> do
+        Record r x i e c tel t cs   -> do
+          pc <- use positivityCheckPragma
+          -- Andreas, 2018-10-27, issue #3327
+          -- Propagate {-# NO_UNIVERSE_CHECK #-} pragma from signature to definition.
+          -- Universe check is performed if both the current value of
+          -- 'universeCheckPragma' AND the one from the signature say so.
+          uc <- use universeCheckPragma
+          uc <- if uc == NoUniverseCheck then return uc else getUniverseCheckFromSig x
```
Comment (andreasabel) [inline src/full/Agda/Syntax/Concrete/Definitions.hs:943]: This line (and my comment on issue #3327) is only relevant for `RecordDef` not for `Record` and should not have been copied here.
