### PR TITLE
Bubble transpSysTel' failures upwards

### LINKED ISSUE #8068: __IMPOSSIBLE__ on dependent pattern match + unrelated holes
Here's a reproduction with no dependencies:
```agda
postulate
  O : Set
  Q : Set
  d : Q → O
  c : Q → O
  Oᴰ : O → Set

data Path : O → O → Set where
  [] : ∀ {a} → Path a a
  _∷_ : ∀ {a} g (p : Path (c g) a) → Path (d g) a

postulate
  Hᴰ : ∀ {o o'}(f : Path o o') → Oᴰ o → Oᴰ o' → Set

foo : ∀ (ıo : ∀ a → Oᴰ a) (ıh : ?) {a b}(f : Path a b) → Hᴰ f (ıo a) (ıo b)
foo ıo ıh [] = {!!}
foo ıo ıh (g ∷ f) = {!!}
```

On Agda 2.8.0 I get the error:
```
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/TypeChecking/Rules/LHS/Unify/LeftInverse.hs:222:7 in Agd-2.8.0-573fd8a0:Agda.TypeChecking.Rules.LHS.Unify.LeftInverse%              
```

### PR DESCRIPTION
**Pull request by plt-amy**
Fixes #8068. The hole with undetermined sort makes actually building the final retraction fall over right at the finish line, even though all of the individual unification steps were translated correctly.

### CODE REVIEW

File: src/full/Agda/TypeChecking/Rules/LHS/Unify/LeftInverse.hs [hunk 1]
```diff
@@ -41,6 +43,7 @@ instance PrettyTCM NoLeftInv where
   prettyTCM WithKEnabled       = fwords "The K rule is enabled"
   prettyTCM SplitOnStrict      = fwords "It splits on a type in SSet"
   prettyTCM SplitOnFlat        = fwords "It splits on a @♭ argument"
+  prettyTCM (CantTransport t)  = fsep $ pwords "The type" <> [prettyTCM t] <> pwords "can not be transported."
```
Comment (andreasabel) [inline src/full/Agda/TypeChecking/Rules/LHS/Unify/LeftInverse.hs]: Maybe without the final "."?

**Review by andreasabel — COMMENTED** [review]
Looks good!

File: src/full/Agda/TypeChecking/Rules/LHS/Unify/LeftInverse.hs (hunk 1 above)
Comment (plt-amy) [reply src/full/Agda/TypeChecking/Rules/LHS/Unify/LeftInverse.hs]: oh yeah i didn't notice all the others didn't have one. 1s
