### PR TITLE
Fix #6476: don't crash on ill-typed applications in DISPLAY terms.

### LINKED ISSUE #6476: Internal error due to display pragma which is not type-correct
When I load the following code and normalise `r` I get an internal error:
```agda
open import Agda.Builtin.Nat

record R : Set where
  constructor c
  field
    m n : Nat

{-# DISPLAY c m = m #-}

r : R
r = c zero zero
```
```
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/TypeChecking/Substitute.hs:87:26 in Agda-2.6.4-…
```
It seems as if Agda tries to apply a literal to something:

https://github.com/agda/agda/blob/4f6a502210fec599501f4e695006047ec9706a2a/src/full/Agda/TypeChecking/Substitute.hs#L67-L97

### PR DESCRIPTION
**Pull request by andreasabel**
Fix #6476 by introducing suspended eliminations in display terms.  This fixes the problem that an ill-typed elimination of a display term would crash Agda.

Also: warn about ill-typed DISPLAY forms in docs.

### CODE REVIEW

File: src/full/Agda/TypeChecking/Substitute.hs [hunk 1]
```diff
@@ -525,14 +525,14 @@ instance Apply FunctionInverse where
   applyE t es = apply t $ fromMaybe __IMPOSSIBLE__ $ allApplyElims es
 
 instance Apply DisplayTerm where
-  apply (DTerm v)          args = DTerm $ apply v args
-  apply (DDot v)           args = DDot  $ apply v args
-  apply (DCon c ci vs)     args = DCon c ci $ vs ++ map (fmap DTerm) args
-  apply (DDef c es)        args = DDef c $ es ++ map (Apply . fmap DTerm) args
+  apply (DTerm' v es)      args = DTerm' v       $ es ++ map Apply args
```
Comment (andreasabel) [inline src/full/Agda/TypeChecking/Substitute.hs:528]: This is the crucial change: do not `apply`, but create suspended application.

**Comment by nad** [comment]
Are `DISPLAY` pragmas used a lot? I think I have one such pragma in the Agda libraries that I maintain: `{-# DISPLAY const x y = x #-}`. I don't think we should spend time on maintaining this feature.

Does your change impact the performance of Agda for code that does not use `DISPLAY` pragmas (but automatically generated display forms)?

**Comment by jespercockx** [comment]
I do use display forms from time to time to work around issues with unreadable error messages when I use instance arguments and `open {{...}}` (see https://github.com/agda/agda/issues/5632). So as long as that problem isn't fixed, I would prefer to keep the current implementation of display pragmas.

**Comment by andreasabel** [comment]
@nad wrote:
> Are `DISPLAY` pragmas used a lot? 

Maybe try a github code search to approximate an answer to this.

> I don't think we should spend time on maintaining this feature.

I already spent the time.  Also, if a feature is there, it should not make Agda crash.

> Does your change impact the performance of Agda for code that does not use `DISPLAY` pragmas (but automatically generated display forms)?

Display forms are only used for printing.  So, the answer is likely no.

@jespercockx wrote:
>  I would prefer to keep the current implementation of display pragmas.

This sentence is slightly ambiguous.  
I read it in a way that you do not want to take away features from `DISPLAY`.
This PR is in line with your wish, and it makes Agda more robust so it crashes less on ill-typed DISPLAY pragmas.
So please test this PR with your developments.

Or shall we merge and have it tested from `master`?

**Comment by jespercockx** [comment]
> This sentence is slightly ambiguous.

Sorry for the ambiguity. I meant that we should not remove DISPLAY pragmas, but the changes in this PR have my full approval!
