### PR TITLE
disable discrim-based instance deferral by default

### LINKED ISSUE #7870: Changelog for 2.8.0: describe changes to instance search
We had a few changes to instance search; please document them in the changelog.

### LINKED ISSUE #7882: Possible regression in 2.8.0-rc1 due to instance resolution
Using:

```
Agda version 2.7.20250510
Built with flags (cabal -f)
 - enable-cluster-counting: unicode cluster counting in LaTeX backend using the ICU library
 - optimise-heavily: extra optimisations
```
the following code fails to typecheck:
```agda
module ex where

open import Agda.Primitive
open import Agda.Builtin.Equality

variable 
  a b c : Level

infixr 1 _⊎_

data _⊎_ (A : Set a) (B : Set b) : Set (a ⊔ b) where
  inj₁ : (x : A) → A ⊎ B
  inj₂ : (y : B) → A ⊎ B

⊎-map₂ : {A B D : Set} → (B → D) → (A ⊎ B → A ⊎ D)
⊎-map₂ g (inj₁ x) = inj₁ x
⊎-map₂ g (inj₂ y) = inj₂ (g y)

record Σ {a b} (A : Set a) (B : A → Set b) : Set (a ⊔ b) where
  constructor _,_
  field
    fst : A
    snd : B fst

open Σ public

infixr 4 _,_

_×_ : ∀ (A : Set a) (B : Set b) → Set (a ⊔ b)
A × B = Σ A λ _ → B

×-map₂ : ∀ {A : Set a} {B : A → Set b} {C : A → Set c} →
        (∀ {x} → B x → C x) → Σ A B → Σ A C
×-map₂ f x = x .fst , f (x .snd)

id : {A : Set} → A → A
id x = x

record Bifunctor (F : Set a → Set b → Set (a ⊔ b)) : Set (lsuc (a ⊔ b)) where
  field
    bimap : ∀ {A A′ : Set a} {B B′ : Set b} → (A → A′) → (B → B′) → F A B → F A′ B′

open Bifunctor ⦃...⦄ public

instance
  Bifunctor-⊎ : Bifunctor {a}{b} _⊎_
  Bifunctor-⊎ .bimap f g (inj₁ x) = inj₁ (f x)
  Bifunctor-⊎ .bimap f g (inj₂ y) = inj₂ (g y)

  Bifunctor-× : Bifunctor {a}{b} _×_
  Bifunctor-× .bimap f g x = f (x .fst) , g (x .snd)

variable
  S : Set
  s s' : S
  Err : Set

module _ (STS : S → S → Set) where
  record Computational Err : Set₀ where
    field
      computeProof : (s : S) → Err ⊎ (Σ S (STS s))
      completeness : (s : S) (s' : S)
        → STS s s' → ⊎-map₂ fst (computeProof s) ≡ inj₂ s'

open Computational ⦃...⦄

data STS* {STS : S → S → Set} : S → S → Set where
  BS-base :
    STS s s' → STS* s s'

module _ {STS : S → S → Set} ⦃ _ : Computational STS Err ⦄ where
  Computational-* : Computational (STS* {STS = STS}) Err
  Computational-* .computeProof s = bimap id (×-map₂ BS-base) (computeProof s) -- fails
  -- Computational-* .computeProof s = bimap ⦃ Bifunctor-⊎ ⦄ id (×-map₂ BS-base) (computeProof s) -- doesn't fail
  Computational-* .completeness s s' (BS-base p)
    with computeProof {STS = STS} s | completeness {STS = STS} _ _ p
  ... | inj₂ x | refl = refl
```
with error:
```
/tmp/agda-bug/ex.agda:77.25-29: error: [MetaCannotDependOn]
Cannot instantiate the metavariable _y.fst_195 to solution fst x
since it contains the variable x
which is not in scope of the metavariable
when checking that the expression refl has type
⊎-map₂ (λ r → fst r) (inj₂ (_y.fst_195 , _y.snd_196)) ≡
inj₂ (fst x)
```

In contrast, `Agda version 2.7.0.1` typechecks the code just fine.

I found two alternative ways of avoiding getting the error in `2.7.20250510`:

1. Commenting out the `Bifunctor-×` instance
2. Passing the instance argument explicitly to `bimap` (see commented out line)

This might be related to #7847.

### PR DESCRIPTION
**Pull request by plt-amy**
but keep it as a flag. i am so tired but also i am going to make this work, mark my words. also fixes #7882 en passant and fixes #7870 properly.

### CODE REVIEW

File: src/full/Agda/TypeChecking/InstanceArguments.hs [hunk 1]
```diff
@@ -186,14 +188,16 @@ initialInstanceCandidates blockOverlap instTy = do
     shouldBlockOverlap bs cands = do
       recursive <- useTC stConsideringInstance
       hack <- useTC stInstanceHack
+      enabled <- useTC (stPragmaOptions . lensOptExperimentalLazyInstances . lensCollapseDefault)
 
       mutual <- caseMaybeM (asksTC envMutualBlock) (pure mempty) \mb ->
         mutualNames <$> lookupMutualBlock mb
 
       pure $! and
```
Comment (andreasabel) [inline src/full/Agda/TypeChecking/InstanceArguments.hs]: Is there a reason for the strictness here?
Normally, I would have formulated this as `andM`...

**Review by andreasabel — COMMENTED** [review]
Thanks!

File: src/full/Agda/TypeChecking/InstanceArguments.hs (hunk 1 above)
Comment (plt-amy) [reply src/full/Agda/TypeChecking/InstanceArguments.hs]: Not really a reason for `$!` over `$`, but most of the conditions are pure/would be awkward to write monadically. (Mistapped the resolve button)

Comment (andreasabel) [reply src/full/Agda/TypeChecking/InstanceArguments.hs]: I pushed a commit trying out the `andM` version.  
Does not look so awkward, what do you think?

Comment (plt-amy) [reply src/full/Agda/TypeChecking/InstanceArguments.hs]: I think it's worse but whatever
