### PR TITLE
Fix #6173 by inserting missing checkModuleName

### LINKED ISSUE #6173: Internal error at Agda/Syntax/Abstract/Name.hs:150:44
[internal-error.zip](https://github.com/agda/agda/files/9739395/internal-error.zip)
Reproduced on Agda HEAD, I've attached a zip file with the files but it's essentially:

```
A.agda
A/Instances.agda -- imports A
B.agda -- imports A.Instances
project.agda-lib -- contains "include: ."
```

Running `agda B.agda` yields:
```
Checking B (/home/gxa1/languages/agda/internal-error/B.agda).
 Checking A.Instances (/home/gxa1/languages/agda/internal-error/A/Instances.agda).
  Checking A (/home/gxa1/languages/agda/internal-error/A.agda).
An internal error has occurred. Please report this as a bug.
Location of the error: __IMPOSSIBLE__, called at src/full/Agda/Syntax/Abstract/Name.hs:150:44 in Agda-2.6.3-1IJKiEdqwYH38p7gkKMyGe:Agda.Syntax.Abstract.Name
```
https://github.com/agda/agda/blob/9672aaaf8d5de0c39b0d2ce50bddfab06bec54bf/src/full/Agda/Syntax/Abstract/Name.hs#L149-L154

Running it once more without removing the `_build` directory leads to a different but equally puzzling error message:
```
Checking B (/home/gxa1/languages/agda/internal-error/B.agda).
/home/gxa1/languages/agda/internal-error/B.agda:1,1-24
The file /home/gxa1/languages/agda/internal-error/A/Instances.agda
can be accessed via several project roots. Both Instances and
A.Instances point to this file.
when scope checking the declaration
  open import A.Instances
```

### PR DESCRIPTION
**Pull request by andreasabel**
- **Fix #6173 by checkModuleName after a module name was reconstructed**
  

- **[cosmetics] use LambdaCase**
  

- **[debug] some Mimer debug printing**

### CODE REVIEW

File: src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs [hunk 1]
```diff
@@ -1533,8 +1533,13 @@ instance ToAbstract (TopLevel [C.Declaration]) where
...
                               C.simpleName $ stringToRawName $
                               rootNameModule file
-                      top <- S.topLevelModuleName
+                      top <- TCM.topLevelModuleName
                                (rawTopLevelModuleNameForQName m)
+                      -- Andreas, 2026-03-01, issue #6173
+                      -- Need to make sure the reconstructed module name
+                      -- matches the one we use to import it,
+                      -- otherwise we get internal errors later.
+                      checkModuleName top src (Just expectedMName)
```
Comment (andreasabel) [inline src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs:1542]: This line fixed the issue.

**Comment by andreasabel** [comment]
Need to investigate https://github.com/agda/agda/actions/runs/22552441524/job/65325408526?pr=8439#step:18:422
> --- (agda2-info-action "*Error*" "Issue2447/Parse-error.agda:1.1-6: error: [AbsentRHSRequiresAbsurdPattern] The right-hand side can only be omitted if there is an absurd pattern, () or {}, in the left-hand side. when checking that the clause wrong has type _1" nil)
> +++ (agda2-info-action "*Error*" "Issue2447c.agda:2.1-29: error: [ModuleNameUnexpected] The name of the top level module does not match the file name. The module Parse-error (at Issue2447/Parse-error.agda:1.1) should probably be named Issue2447.Parse-error when scope checking the declaration import Issue2447.Parse-error" nil)
