### PR TITLE
Fix for #5462

### LINKED ISSUE #5462: Internal error caused by a REWRITE on a projection-like function
The following is a stand-alone example extracted from the actual code that caused the internal error.

```agda
{-# OPTIONS --rewriting --confluence-check #-}
module Test where

open import Agda.Primitive public

infix 4 _≣_
data _≣_
  {l : Level}
  {A : Set l}
  : -------------------------------
  {B : Set l}(x : A)(y : B) → Set l
  where
  instance refl : {x : A} → x ≣ x

{-# BUILTIN REWRITE _≣_ #-}

postulate
  𝔸   : Set

data Swap {l : Level}(A : Set l) : Set l where
  action :
    (swap : 𝔸 → 𝔸 → A → A)
    (swap-id : (a : 𝔸)(x : A) → swap a a x ≣ x)
    → -----------------------------------------
    Swap A

infix 6 _≀_
_≀_ :
  {l : Level}
  {A : Set l}
  ⦃ _ : Swap A ⦄
  (a b : 𝔸)
  → ------------
  A → A
_≀_ ⦃ action swap _ ⦄ = swap

data Swap₁
  {l m : Level}
  {A : Set l}
  ⦃ _ : Swap A ⦄
  (B : A → Set m)
  : -------------
  Set (l ⊔ m)
  where
  action₁ :
    (swap₁ :
      (a b : 𝔸)
      {x : A}
      → -----------------
      B x → B ((a ≀ b) x))
    (swap₁-id :
      (a : 𝔸)
      {x : A}
      (y : B x)
      → --------------
      swap₁ a a y ≣ y)
    → --------------------
    Swap₁ B

infix 6 _≀₁_
_≀₁_ :
  {l m : Level}
  {A : Set l}
  ⦃ _ : Swap A ⦄
  {B : A → Set m}
  ⦃ sw₁ : Swap₁ B ⦄
  (a b : 𝔸)
  {x : A}
  → -----------------
  B x → B ((a ≀ b) x)
_≀₁_ ⦃ sw₁ = action₁ swap₁ _ ⦄ = swap₁

≀₁id :
  {l m : Level}
  {A : Set l}
  ⦃ _ : Swap A ⦄
  {B : A → Set m}
  ⦃ sw₁ : Swap₁ B ⦄
  (a : 𝔸)
  {x : A}
  (y : B x)
  → ---------------
  (a ≀₁ a) y ≣ y
≀₁id ⦃ sw₁ = action₁ _ swap₁-id ⦄  = swap₁-id

{-# REWRITE ≀₁id #-}
```
When checking this with Agda 2.6.2, one gets the message:

    An internal error has occurred. Please report this as a bug.
    Location of the error: __IMPOSSIBLE__, called at  src/full/Agda/TypeChecking/Rewriting/NonLinPattern.hs:134:41 in Agda2.6.26ce032c1:Agda.TypeChecking.Rewriting.NonLinPattern

### PR DESCRIPTION
**Pull request by jespercockx**
This fixes #5462 by throwing an error when trying to add a rewrite rule with a projection-like head, with a suggestion to turn on `--no-projection-like`. A proper treatment of projection-like functions in rewriting will have to wait until the fix of #1981.

### CODE REVIEW

File: src/full/Agda/TypeChecking/Rewriting.hs [hunk 1]
```diff
@@ -352,7 +352,17 @@ checkRewriteRule q = do
     checkAxFunOrCon :: QName -> Definition -> TCM ()
     checkAxFunOrCon f def = case theDef def of
       Axiom{}        -> return ()
-      Function{}     -> return ()
+      def@Function{} -> whenJust (funProjection def) $ \proj ->
+        case projProper proj of
+          Just{} -> typeError . GenericDocError =<< hsep
+            [ prettyTCM q , " is not a legal rewrite rule, since the head symbol"
```
Comment (andreasabel) [inline src/full/Agda/TypeChecking/Rewriting.hs:358]: Is the extra space in the string after `q` intended here?  (There is none after `f`.)

File: src/full/Agda/TypeChecking/Rewriting.hs [hunk 2]
```diff
@@ -352,7 +352,17 @@ checkRewriteRule q = do
...
+            , prettyTCM f , "is a projection."
```
Comment (andreasabel) [inline src/full/Agda/TypeChecking/Rewriting.hs]: I suppose there should not be a final `.` in the error message, since it continues with `when checking ...`.

**Review by andreasabel — CHANGES_REQUESTED** [review]
Thanks for fixing all the contexts on the way!

I have some error message nitpick...

File: src/full/Agda/TypeChecking/Rewriting.hs [hunk 3]
```diff
@@ -352,7 +352,17 @@ checkRewriteRule q = do
...
+      def@Function{} -> whenJust (funProjection def) $ \proj ->
+        case projProper proj of
+          Just{} -> typeError . GenericDocError =<< hsep
+            [ prettyTCM q , " is not a legal rewrite rule, since the head symbol"
+            , prettyTCM f , "is a projection"
+            ]
+          Nothing -> typeError . GenericDocError =<< hsep
+            [ prettyTCM q , " is not a legal rewrite rule, since the head symbol"
+            , prettyTCM f , "is a projection-like function."
+            , "You can turn off the projection-like optimization with the flag --no-projection-like"
```
Comment (andreasabel) [inline src/full/Agda/TypeChecking/Rewriting.hs:364]: Once
- #6204 

lands, this error could also suggest `{-# NOT_PROJECTION_LIKE f #-}`.
