### PR TITLE
Fix #6138 Refine the error message about failure of overloaded resolution

### LINKED ISSUE #6138: Extremely unhelpful error message cannot resolve overloaded projection because principal argument is not of record type
The following program works, but fails with an unhelpful error message when the commented line is uncommented:

```agda
{-# OPTIONS --type-in-type #-}

module Test where

  module _ where
    record Category : Set where
      infixr 0 _⇒_
      infixr 5 _∘_
      field
        Obj : Set
        _⇒_ : Obj → Obj → Set
        _∘_ : {a b c : Obj} → (g : b ⇒ c) → (f : a ⇒ b) → a ⇒ c


    open import Relation.Binary.Structures using (IsEquivalence)

    record LawfulCategory (C : Category) : Set where
      open Category C

      infix 0 _≈_

      field
        _≈_ : {a b : Obj} → a ⇒ b → a ⇒ b → Set
        ≈-equiv : {a b : Obj} → IsEquivalence (_≈_ {a} {b})

      module HomReasoning {A B : Obj} where
        open IsEquivalence (≈-equiv {A} {B}) public


  module _ {C D : Category} (LD : LawfulCategory D) where
    open Category C renaming (Obj to ObjC; _⇒_ to _⇒_;  _∘_ to _∘_)

    record Homomorphism : Set where
      open LawfulCategory LD
      open Category D renaming (Obj to ObjD; _⇒_ to _⊸_;  _∘_ to _⊚_)
      field
        obj-map : ObjC → ObjD
        hom-map : {a b : ObjC} → (a ⇒ b) → obj-map a ⊸ obj-map b
        ∘-map : {a b c : ObjC} {g : b ⇒ c} {f : a ⇒ b} → hom-map (g ∘ f) ≈ hom-map g ⊚ hom-map f


    open import Relation.Binary.Structures using (IsEquivalence)

    open Homomorphism
    open LawfulCategory.HomReasoning LD using (sym; refl; trans)
    -- open LawfulCategory
    open LawfulCategory LD

    to-from : {a b c : ObjC} {f : a ⇒ b} {g : b ⇒ c} → (h : Homomorphism) → hom-map h (g ∘ f) ≈ hom-map h (g ∘ f)
    to-from h = trans (∘-map h) (sym (∘-map h))
```

When `open LawfulCategory` is uncommented, the program fails with:

```
/home/sandy/prj/conceptual-mathematics/src/Test.agda:50,77-114
Cannot resolve overloaded projection _≈_ because principal argument
is not of record type
when checking that the expression
hom-map h (g ∘ f) ≈ hom-map h (g ∘ f) has type _53
```

I spent about an hour trying to debug what went wrong here. It'd be extremely helpful if agda dumped the types of whatever `_≈_` projections were in scope, eg maybe:

```
/home/sandy/prj/conceptual-mathematics/src/Test.agda:50,77-114
Cannot resolve overloaded projection _≈_ because dispatch is ambiguous
when checking that the expression
hom-map h (g ∘ f) ≈ hom-map h (g ∘ f) has type _53
Could not disambiguate between
- _≈_ : {a b : Obj} → a ⇒ b → a ⇒ b → Set
    brought into scope on line 47
- _≈_ : {C : Category} → LawfulCategory C → {a b : Obj C} → _⇒_ C a b → _⇒_ C a b → Set
    brought into scope on line 46
```

which would help point out the double import.

---

Agda version 2.6.3-7bda162

### PR DESCRIPTION
**Pull request by knisht**
Basically, all sorts of errors that are printed via `refuseProj` are about ambiguous record fields. Sometimes the error messages indeed became unclear, especially if they did not talk about existence of multiple same-named definitions in the scope.

### CODE REVIEW

File: src/full/Agda/TypeChecking/Rules/Application.hs [hunk 1]
```diff
@@ -1386,16 +1386,31 @@ inferOrCheckProjAppToKnownPrincipalArg e o ds args mt k v0 ta mpatm = do
...
+
+refuseProjNotApplied, refuseProjNoMatching :: List1 QName -> TCM a
+refuseProjNotApplied    ds = refuseProj ds $ fwords "it is not applied to a visible argument"
+refuseProjNoMatching    ds = refuseProj ds $ fwords "no matching candidate found"
+refuseProjNotRecordType :: List1 QName -> Maybe Term -> Type -> TCM a
+refuseProjNotRecordType ds pValue pType = do
+    let dType = quotes $ reify pType >>= prettyA
+    let dValue = caseMaybe pValue (return empty) (\term -> quotes (reify term >>= prettyA))
+    refuseProj ds $ fsep $
+      ["principal argument", dValue, "has type", dType, " while it should be of record type"]
```
Comment (plt-amy) [inline src/full/Agda/TypeChecking/Rules/Application.hs]:
```suggestion
      ["principal argument", dValue, "has type", dType, "while it should be of record type"]
```

**Review by plt-amy — APPROVED** [review]
This is great, thank you! I found a minor nit to pick with the formatting of the new error message. I also don't think it's usual for us to print types `'in quotes'` but that's okay by me :slightly_smiling_face:

File: test/Fail/Issue1944-UnappliedOverloadedProjectionNotRecord.err [hunk 2]
```diff
@@ -1,4 +1,7 @@
 Issue1944-UnappliedOverloadedProjectionNotRecord.agda:15,8-9
-Cannot resolve overloaded projection f because principal argument
-is not of record type
-when checking that the expression f has type A → A
+Cannot resolve overloaded projection 'f' because
+principal argument has type 'A₁'  while it should be of record type
+Signatures in the scope: 
+- f : {@0 B : Set} → R B → B
+- f : {@0 B : Set} → S B → B
+when checking that the expression f has type A₁ → A₁
```
Comment (andreasabel) [inline test/Fail/Issue1944-UnappliedOverloadedProjectionNotRecord.err:7]: `A₁ → A₁` is looks worse at first in comparison to `A → A`, but when looking at the testcase, there is an `A` in scope which is unrelated, so `A₁` could fit some taste better as it is distinct to `A`, even though the user didn't write `A₁` anywhere.
In the olden days, we printed such as `.A → .A` where the preceding `.` was used for "not in scope", but this was also confusing.  Best would be colored printing, then we could have a different color for out-of-scope identifiers.

(This is just a random remark.  Nothing to be changed here.)

File: test/Fail/Issue1944-instance.err [hunk 3]
```diff
@@ -1,4 +1,8 @@
 Issue1944-instance.agda:23,14-20
-Cannot resolve overloaded projection test because principal
-argument is not of record type
+Cannot resolve overloaded projection 'test' because
+principal argument 'x' has type 'A'
+ while it should be of record type
+Signatures in the scope: 
+- test : ({A = A₁ : Set} ⦃ r : Testable A₁ ⦄ → A₁ → Bool)
+- test : ({@0 A = A₁ : Set} → Testable A₁ → A₁ → Bool)
```
Comment (andreasabel) [inline test/Fail/Issue1944-instance.err:6]: Could the new "Signatures in scope" part maybe be indented (`nest 2`)?  It breaks a bit the flow of its surrounding sentence, so maybe indentation would mark it as "bracketed phrase".

**Review by andreasabel — CHANGES_REQUESTED** [review]
Excellent work!

I added some nitpicking to Amelia's nitpicking...

File: test/Fail/Issue1944-UnappliedOverloadedProjectionNotRecord.err (hunk 2 above)
Comment (nad) [reply test/Fail/Issue1944-UnappliedOverloadedProjectionNotRecord.err:7]: > Best would be colored printing, then we could have a different color for out-of-scope identifiers.

I encountered something like that in Isabelle once, and it took me a while to realise that two "identical" pieces of code had differently coloured variables.

File: test/Fail/Issue1944-instance.err (hunk 3 above)
Comment (knisht) [reply test/Fail/Issue1944-instance.err:6]: Sure.

**Comment by knisht** [comment]
@plt-amy Thanks, I removed quotation. It just feels weird to me to mix terms with regular english text, so I felt a need to outline the terms somehow. But it is more important to stick with the same style everywhere.
In Arend we have highlighting of terms in the error messages (which makes go-to-definition and other IDE features work there), so maybe there is a way to employ something similar in emacs. This is outside the scope of this issue though.

File: src/full/Agda/TypeChecking/Rules/Application.hs [hunk 4]
```diff
@@ -1497,16 +1497,30 @@ inferOrCheckProjAppToKnownPrincipalArg e o ds args mt k v0 ta mpatm = do
...
+  let nameRaw = pretty $ A.nameConcrete $ A.qnameName $ List1.head ds
+  doc <- vcat
+    [ fsep
+      [ text "Cannot resolve overloaded projection"
+      , nameRaw
+      , text "because"
+      , reason
+      ]
+    , nest 2 (text "Signatures in the scope:")
+    , vcat $ fmap (typeOfConst >=> reify >=> prettyA >=> (\typeDoc -> text "-" <+> nest 2 (nameRaw <+> text ":" <+> pure typeDoc))) ds
```
Comment (andreasabel) [inline src/full/Agda/TypeChecking/Rules/Application.hs]: Use prettyTCM.

File: src/full/Agda/TypeChecking/Rules/Application.hs [hunk 5]
```diff
@@ -1497,16 +1497,30 @@ inferOrCheckProjAppToKnownPrincipalArg e o ds args mt k v0 ta mpatm = do
...
+    ]
+  typeError $ GenericDocError $ doc
```
Comment (andreasabel) [inline src/full/Agda/TypeChecking/Rules/Application.hs]: Maybe add an error to the `TypeError` type.

**Review by andreasabel — APPROVED** [review]
Approved, but Konstantin was positive to implement my last two suggestions.

File: test/Fail/Issue1944-UnappliedOverloadedProjectionNotRecord.err (hunk 2 above)
Comment (andreasabel) [reply test/Fail/Issue1944-UnappliedOverloadedProjectionNotRecord.err:7]: We should also distinguish clashing identifiers by a suffix, where possible, of course.

File: src/full/Agda/TypeChecking/Rules/Application.hs (hunk 1 above)
Comment (andreasabel) [reply src/full/Agda/TypeChecking/Rules/Application.hs]: I think this has been addressed.

File: src/full/Agda/TypeChecking/Rules/Application.hs (hunk 5 above)
Comment (andreasabel) [reply src/full/Agda/TypeChecking/Rules/Application.hs]: Thanks!

File: src/full/Agda/TypeChecking/Rules/Application.hs (hunk 4 above)
Comment (andreasabel) [reply src/full/Agda/TypeChecking/Rules/Application.hs]: I took the liberty to rewrite this Kleisli composition sequence into something pointfull, see [`b892a4c` (#6346)](https://github.com/agda/agda/pull/6346/commits/b892a4c008d67b24dfe0a549061c56bfb8e3d029)
