### PR TITLE
Fix for issue #7113

### LINKED ISSUE #7113: Instance resolution runs too late, leads to `with`-abstraction failure
I have a situation where a `rewrite` unexpectedly does nothing. How is this possible? I would expect a failed `rewrite` to give an error message, otherwise I expect the goal type to change.

I have minimised the proof script to the following:

```agda
module Gamma where

open import Relation.Binary.PropositionalEquality

record Semiring : Set₁ where
  field
    grade : Set
    1R           : grade
    _*_          : grade → grade → grade
    leftUnit*    : {r : grade} → 1R * r ≡ r
    -- [...]

open Semiring {{...}}

foo : {{R : Semiring}} {r : grade} → 1R * r ≡ r
foo {r = r} rewrite leftUnit* {r} = {!   !}
```

Without the `rewrite`, the goal is `(R Semiring.* Semiring.1R R) r ≡ r`. Adding the `rewrite` neither changes the goal, nor gives any error message.

Note: This is easy enough to work around, but I wanted to understand what is going on here.

#### Addendum

```
$ agda --version
Agda version 2.6.4.1
```

### PR DESCRIPTION
**Pull request by jespercockx**
This fixes #7113 by always solving awake constraints after checking a `with`-expression, thus solving any instance arguments contained therein.

### CODE REVIEW

File: src/full/Agda/TypeChecking/Rules/Term.hs [hunk 1]
```diff
@@ -1572,20 +1571,21 @@ inferExprForWith (Arg info e) = verboseBracket "tc.with.infer" 20 "inferExprForW
...
+      (v, t) <- case unEl t0 of
         Def d vs -> do
           isDataOrRecordType d >>= \case
             Nothing -> return (v, t)
             Just{}  -> do
               (args, t1) <- implicitArgs (-1) notVisible t
-              -- #6868: trigger instance search if we inserted any instance arguments
-              when (any isInstance args) $ solveAwakeInstanceConstraints
               return (v `apply` args, t1)
         _ -> return (v, t)
```
Comment (andreasabel) [inline src/full/Agda/TypeChecking/Rules/Term.hs:1585]: This `v` is now more reduced than before, is it?  (A priori that could affect some error messages, maybe that was why there was a `v0`...)

File: src/full/Agda/TypeChecking/Rules/Term.hs [hunk 2]
```diff
@@ -1558,12 +1558,11 @@ inferExprForWith (Arg info e) = verboseBracket "tc.with.infer" 20 "inferExprForW
...
     traceCall (InferExpr e) $ do
-      -- With wants type and term fully instantiated!
-      (v, t) <- instantiateFull =<< inferExpr e
-      v0 <- reduce v
+      (v, t) <- inferExpr e
+      v <- reduce v
       -- Andreas 2014-11-06, issue 1342.
       -- Check that we do not `with` on a module parameter!
-      case v0 of
+      case v of
```
Comment (andreasabel) [inline src/full/Agda/TypeChecking/Rules/Term.hs:1565]: To avoid the extra `v0`, maybe do `reduce v >>= \case`...

File: src/full/Agda/TypeChecking/Rules/Term.hs (hunk 1 above)
Comment (jespercockx) [reply src/full/Agda/TypeChecking/Rules/Term.hs:1585]: Yes, but I checked all the places where this function is used (which is a grand total of 2) and in both places we continue by normalizing it. So returning the reduced version here is fine, and it could save a lot of work if computing the whnf is expensive.

File: src/full/Agda/TypeChecking/Rules/Term.hs (hunk 2 above)
Comment (jespercockx) [reply src/full/Agda/TypeChecking/Rules/Term.hs:1565]: but then we would not have access to the reduced `v` in the rest of the `do` block!

File: src/full/Agda/TypeChecking/Rules/Term.hs (hunk 1 above)
Comment (andreasabel) [reply src/full/Agda/TypeChecking/Rules/Term.hs:1585]: I can confirm.

**Review by andreasabel — APPROVED** [review]
Thanks, let's try this!

File: src/full/Agda/TypeChecking/Rules/Term.hs [hunk 3]
```diff
@@ -1558,9 +1558,8 @@ inferExprForWith (Arg info e) = verboseBracket "tc.with.infer" 20 "inferExprForW
     reportSDoc "tc.with.infer" 20 $ "inferExprforWith " <+> prettyTCM e
     reportSLn  "tc.with.infer" 80 $ "inferExprforWith " ++ show (deepUnscope e)
     traceCall (InferExpr e) $ do
-      -- With wants type and term fully instantiated!
-      (v, t) <- instantiateFull =<< inferExpr e
       v0 <- reduce v
+      (v, t) <- inferExpr e
```
Comment (andreasabel) [inline src/full/Agda/TypeChecking/Rules/Term.hs:1561]: This commit looks ill-formed (`v` used before definition) so I'll squash.

File: src/full/Agda/TypeChecking/Rules/Term.hs [hunk 4]
```diff
@@ -1558,12 +1558,11 @@ inferExprForWith (Arg info e) = verboseBracket "tc.with.infer" 20 "inferExprForW
     reportSDoc "tc.with.infer" 20 $ "inferExprforWith " <+> prettyTCM e
     reportSLn  "tc.with.infer" 80 $ "inferExprforWith " ++ show (deepUnscope e)
     traceCall (InferExpr e) $ do
-      -- With wants type and term fully instantiated!
-      (v, t) <- instantiateFull =<< inferExpr e
```
Comment (andreasabel) [inline src/full/Agda/TypeChecking/Rules/Term.hs:1562]: Even though we `normalise` later, we could need this `instantiateFull` since it does eta-contraction, which normalisation does not do.

File: src/full/Agda/TypeChecking/Rules/Term.hs [hunk 5]
```diff
@@ -1558,12 +1558,11 @@ inferExprForWith (Arg info e) = verboseBracket "tc.with.infer" 20 "inferExprForW
...
-      v0 <- reduce v
+      (v, t) <- inferExpr e
+      v <- reduce v
       -- Andreas 2014-11-06, issue 1342.
       -- Check that we do not `with` on a module parameter!
-      case v0 of
+      case v of
         Var i [] -> whenM (isModuleFreeVar i) $ do
```
Comment (andreasabel) [inline src/full/Agda/TypeChecking/Rules/Term.hs:1566]: The missing eta-contraction ~~could~~ also backfire(s) here when we now do not hit a variable but the eta-expansion of one.

Agda 2.6.4.2 let's this through:
```
module _ (A : Set) (a : A → A) where

test : Set
test with (λ (x : A) → a x)
... | _ = A
```
Former Agdas complain: 
```
Cannot `with` on expression λ (x : A) → a x which reduces to
variable a bound in a module telescope (or patterns of a parent
clause)
when inferring the type of λ (x : A) → a x
```
Unfortunately, #1342 and #2324 didn't include this test.

**Review by andreasabel — COMMENTED** [review]
In the light of #7148 the flaw in the refactoring here becomes apparent: lack of eta-contraction formerly performed by `instantiateFull`. 
I also keep forgetting that normalisation isn't just a beefed-up `instantiateFull`, its tempting to think in terms of a diamond-shaped order `normalise > instantiateFull, reduce > instantiate` (which isn't the case).
