### PR TITLE
[ fix #5727 ] Normalise level expressions before checking convertibility

### LINKED ISSUE #5727: Reducing universe levels before checking is not sufficient
To check if two `Level` terms are equal, Agda first reduces them to check if they are syntactically equal (L1450) below 

https://github.com/agda/agda/blob/a0b3eea0c19c47ffbe2be525316311f5795d760d/src/full/Agda/TypeChecking/Conversion.hs#L1450-L1454

which however seems insufficient, if they do have the same normal form but different head normal form. 

### Example
Unfortnutely, I don't have a minimal working example, though. Here is the actual code of our working project exhibiting this insufficiency:

https://github.com/Zekt/Type-Embellishment/blob/3f75a36646afdbea2db1a0efd6d899fd6b401ab6/src/Generics/Safe/RecursionScheme.agda#L49

On line 49, the hole can be refined by `args` but consequently Agda complains that
```agda
Failed to solve the following constraints:
  foldr lzero _⊔_ (map (λ _ → ℓ) (PDataD.struct (DataD.applyL D ℓs)))
  ⊔
  foldr lzero _⊔_
  (map (λ x → foldr lzero _⊔_ (map ρ-level x))
   (PDataD.struct (DataD.applyL D ℓs)))
  ⊔
  foldr lzero _⊔_
  (map (λ x → foldr lzero _⊔_ (map σ-level x))
   (PDataD.struct (DataD.applyL D ℓs)))
    = foldr lzero _⊔_ (map max-π (PDataD.struct (DataD.applyL D ℓs))) ⊔
      foldr lzero _⊔_ (map max-σ (PDataD.struct (DataD.applyL D ℓs)))
      ⊔
      foldr lzero _⊔_ (map (λ _ → ℓ) (PDataD.struct (DataD.applyL D ℓs)))
    (blocked on _ℓ_165)
```
However, each subterm on the RHS, i.e.

1. `foldr lzero _⊔_ (map max-π (PDataD.struct (DataD.applyL D ℓs)))`
2. `foldr lzero _⊔_ (map max-σ (PDataD.struct (DataD.applyL D ℓs)))`
3. `foldr lzero _⊔_ (map (λ _ → ℓ) (PDataD.struct (DataD.applyL D ℓs)))`

normalises to

1. `foldr lzero _⊔_ (map (λ x → foldr lzero _⊔_ (map ρ-level x)) (PDataD.struct (DataD.applyL D ℓs)))` (equal to the 2nd subterm of the LHS)
2. `foldr lzero _⊔_ (map (λ x → foldr lzero _⊔_ (map σ-level x)) (PDataD.struct (DataD.applyL D ℓs)))` (equal to the 3rd subterm)
3.  the same term which is equal to the first subterm of the LHS

respectively (checked by `C-c C-n` inside the hole), so the LHS and the RHS are judgementally equal.

### Possible solution
Replacing `reduce` by `normalise` below does allow Agda to see they are the same term. 

https://github.com/agda/agda/blob/a0b3eea0c19c47ffbe2be525316311f5795d760d/src/full/Agda/TypeChecking/Conversion.hs#L1450

Indeed, these two terms are reported syntactically equal by turning on the verbose option ` -v tc.conv.level:60`
```agda
equalLevel
  (foldr lzero _⊔_
   (map (λ _ → ℓ) (PDataD.struct (DataD.applyL D ℓs)))
   ⊔
   foldr lzero _⊔_
   (map (λ x → foldr lzero _⊔_ (map ρ-level x))
    (PDataD.struct (DataD.applyL D ℓs)))
   ⊔
   foldr lzero _⊔_
   (map (λ x → foldr lzero _⊔_ (map σ-level x))
    (PDataD.struct (DataD.applyL D ℓs)))) ==
  (foldr lzero _⊔_ (map max-π (PDataD.struct (DataD.applyL D ℓs))) ⊔
   foldr lzero _⊔_ (map max-σ (PDataD.struct (DataD.applyL D ℓs)))
   ⊔
   foldr lzero _⊔_
   (map (λ _ → ℓ) (PDataD.struct (DataD.applyL D ℓs))))
checkSyntacticEquality returns True
```
Shall we use normalisation instead of reduction before syntactic checking?

### PR DESCRIPTION
**Pull request by L-TChen**
1. Add `checkSyntacticEquality'` that always checks without considering fuel
2. Use normalisation for the universe check
3. Remove subsumed terms right after normalisation

Some small test cases are being cooked, but I have been using this patch for a while in a research project.

### CODE REVIEW

**Comment by L-TChen** [comment]
It seems that normalising levels is actually faster than reducing levels only, judging from the last two commits on the `master` branch.

File: src/full/Agda/TypeChecking/SyntacticEquality.hs [hunk 1]
```diff
@@ -70,19 +71,40 @@ checkSyntacticEquality
...
+      Term -> Term ->
+      (Term -> Term -> ReduceM a) ->
+      (Term -> Term -> ReduceM a) ->
+      ReduceM a #-}
+{-# SPECIALIZE checkSyntacticEquality' ::
+      Type -> Type ->
+      (Type -> Type -> ReduceM a) ->
+      (Type -> Type -> ReduceM a) ->
+      ReduceM a #-}
+checkSyntacticEquality'
```
Comment (nad) [inline src/full/Agda/TypeChecking/SyntacticEquality.hs:97]: Please add some documentation.

Comment (L-TChen) [reply src/full/Agda/TypeChecking/SyntacticEquality.hs:97]: Done.

**Review by andreasabel — APPROVED** [review]
Thanks!
