### PR TITLE
Fixed #6398

### LINKED ISSUE #6398: Windows line ending messes up syntax highlighting, code ranges and error-jumps
I've received some Agda files from a windows user which I've been trying to type-check. Syntax highlighting in emacs was completely messed up and the error messages I got did not have correct code ranges (in the Agda output) and clicking them in emacs sent me to a *different* but still wrong code range.
Opening the concerned files in gedit and resaving them with Linux/Unix line ending encoding solved the issue. (Gedit can also save with Windows encoding, which may help out to reproduce the bug.)

I'm on Agda version 2.6.4-2f0ea06

---

Please make sure it is actually a problem with Agda or its documentation. For user questions, the [mailing list](https://lists.chalmers.se/mailman/listinfo/agda) or the [chat](https://agda.zulipchat.com) are better fora.

Please take some time to search through the exising issues whether the problem has already been reported.  If it is already an open issue, you might confine yourself with just adding your problem instance as a comment there.

For opening a new issue, please make sure you can check the following boxes:

* [X] My report includes the version of Agda (and Emacs, GHC, and OS versions where relevant).

* [X] The issue can be reproduced with the _latest version_ of Agda (either [released](https://wiki.portal.chalmers.se/agda/Main/Download) or `master` branch).
      Note: We do not fix issues in older versions of Agda.

* [ ] I have supplied all information so the bug can be easily reproduced (in particular, the reproducer is a complete Agda file).

Note: The best reproducers are those only using the `Agda.Builtin` and `Agda.Primitive` modules shipped with Agda.

### PR DESCRIPTION
**Pull request by nad**
See #6398.

### CODE REVIEW

**Comment by nad** [comment]
This commit has been cherry-picked for the release-2.6.3 branch.

File: src/full/Agda/Utils/IO/UTF8.hs [hunk 1]
```diff
@@ -21,10 +21,10 @@ import qualified System.IO.Error as E
 -- line or paragraph separators into '\n'.
 
 convertLineEndings :: Text -> Text
-convertLineEndings = T.map convert . convertNLCR
```
Comment (andreasabel) [inline src/full/Agda/Utils/IO/UTF8.hs:24]: This function might also lend itself to some unit testing...
