### PR TITLE
Fix #7906: use compiled clause reducer in termination checker

### LINKED ISSUE #7906: Manually eta-expanding clause makes termination checking fail
cc @andreasabel 

```agda
open import Agda.Builtin.Equality
open import Agda.Builtin.Sigma

open Agda.Primitive

private variable
  l l' : Level
  A B C : Set l
  x y z : A
  f : A → B
  P : A → Set l

fibre : (A → B) → B → Set _
fibre {A = A} f y = Σ A λ x → f x ≡ y

subst : (P : A → Set l) → x ≡ y → P x → P y
subst P refl x = x

postulate
  Whatever : {A : Set l} → A → Set
  whatever : {A : Set l} (x : A) → Whatever x

record is-iso {A : Set l} {B : Set l'} (f : A → B) : Set (l ⊔ l') where
  field
    from : B → A
    linv : Whatever (λ x → from (f x))

open is-iso

_≃_ : Set l → Set l → Set l
A ≃ B = Σ (A → B) is-iso

module _ {A : Set l} {B : Set l} {f : A → B} {P : B → Set l} where
  shuffle : ((b : B) → fibre f b → P b) ≃ ((a : A) → P (f a))

  shuffle .fst g a = g (f a) (a , refl) -- fails
  -- shuffle .fst = λ g a → g (f a) (a , refl) -- works
  shuffle .snd = go where
    go : is-iso (shuffle .fst)
    go .from g b x = subst P (x .snd) (g (x .fst))
    go .linv = whatever {!   !}
```

### PR DESCRIPTION
**Pull request by andreasabel**
Commits:
- Refactor: remember in `Cl` which `Clause` it comes from
- Refactor: remember in `Done `which `Clause` it comes from
- Refactor: remember `ClauseRecursive` in `Done`
- Refactor: remember `ClauseRecursive` in `Cl`
- Refactor: `ClauseRecursive` enum type rather than `Maybe Bool`
  No good deed goes unpunished.
- Refactor: RecCheck: put `ClauseRecursive` into compile clauses
- Refactor: ability to turn off `RecursiveReductions` in case trees
- Fix #7906 by using compiled-clause reduction in termination checker
- Clean: remove `envTermCheckReducing`

### CODE REVIEW

File: src/full/Agda/Syntax/Internal.hs [hunk 1]
```diff
@@ -385,6 +385,30 @@ type Blocked_ = Blocked ()
...
+-- | Does the clause body contain calls to any of the mutually recursive functions?
+data ClauseRecursive
+  = YesRecursive
+      -- ^ Definitely a call to a mutually recursive function.
+  | NotRecursive
+      -- ^ Definitely no call to a mutually recursive function.
+  | MaybeRecursive
+      -- ^ Possibly a recursive call.
+      --   Could be that the analysis has not run yet,
+      --   or the clause body contains a meta
```
Comment (andreasabel) [inline src/full/Agda/Syntax/Internal.hs]: This "body contains a meta" is not actually implemented.

File: src/full/Agda/TypeChecking/CompiledClause/Compile.hs [hunk 2]
```diff
@@ -42,7 +42,7 @@ compileClauses' q recpat cs mSplitTree = do
 
   -- Throw away the unreachable clauses (#2723).
   let notUnreachable = (Just True /=) . clauseUnreachable
-  cs <- map unBruijn <$> normaliseProjP (filter notUnreachable cs)
+  cs <- map unBruijn <$> normaliseProjP (filter (notUnreachable .snd) $ zip [0..] cs)
```
Comment (andreasabel) [inline src/full/Agda/TypeChecking/CompiledClause/Compile.hs]: `. snd`

File: src/full/Agda/TypeChecking/Serialise/Instances/Internal.hs [hunk 3]
```diff
@@ -501,16 +501,19 @@ instance EmbPrj OpaqueBlock where
   value = valueN (\id uf -> let !unfolding = HashSet.fromList uf
                             in OpaqueBlock id unfolding mempty Nothing)
 
+instance EmbPrj ClauseRecursive
```
Comment (andreasabel) [inline src/full/Agda/TypeChecking/Serialise/Instances/Internal.hs:504]: Bump the serialize version.

**Review by szumixie — APPROVED** [review]
