### PR TITLE
Issue 3672: better error messages for generalize easter eggs

### LINKED ISSUE #3672: Better error messages for generalize easter eggs
The following code triggers an internal error:
```agda
data C (A : Set) : Set where
  c : (x : A) → C A

data D : Set where

data E (A : Set) : Set where
  e : A → E A

postulate
  F : {A : Set} → A → Set

G : {A : Set} → C A → Set
G (c x) = E (F x)

postulate
  H : {A : Set} → (A → Set) → C A → Set
  f : {A : Set} {P : A → Set} {y : C A} → H P y → (x : A) → G y → P x
  g : {A : Set} {y : C A} {P : A → Set} → ((x : A) → G y → P x) → H P y

variable
  A : Set
  P : A → Set
  x : A
  y : C A

postulate
  h : {p : ∀ x → G y → P x} → (∀ x (g : G y) → F (p x g)) → F (g p)

id : (A : Set) → A → A
id _ x = x

i : (h : H P y) → (∀ x (g : G y) → F (f h x g)) → F (g (f h))
i x y = id (F (g (f x))) (h y)
```
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/TypeChecking/Substitute.hs:81
```
This error is not triggered by Agda 2.5.4.2.20190310.

### PR DESCRIPTION
**Pull request by UlfNorell**
Fixes #3672

### CODE REVIEW

File: src/full/Agda/TypeChecking/Generalize.hs [hunk 1]
```diff
@@ -357,15 +357,18 @@ pruneUnsolvedMetas genRecName genRecCon genTel genRecFields interactionPoints is
...
     prepruneError x code = do
       r <- getMetaRange x
-      let msg = "Congratulations! You have found an easter egg (#" ++ code ++ "). " ++
-                "Be the first to submit a self-contained test case (max 50 lines of code) " ++
-                "producing this error message to https://github.com/agda/agda/issues/3672 " ++
-                "to receive a small prize."
-          cause = "The error is caused by complicated dependencies between unsolved " ++
-                  "metavariables and generalized variables. In particular, this meta:"
+      let msg = case code of
+            "RFCX" -> "Failed to generalize because some of the generalized variables depend on an " ++
```
Comment (andreasabel) [inline src/full/Agda/TypeChecking/Generalize.hs]: Shouldn't we have a enum type instead of these string constants?

Comment (UlfNorell) [reply src/full/Agda/TypeChecking/Generalize.hs]: The strings are indeed a bit icky. If Haskell had local datatypes, an enum type would be nice. Added three separate functions instead.

**Review by andreasabel — APPROVED** [review]
