### PR TITLE
Fix mutual information not being set properly by the positivity checker

### LINKED ISSUE #7133: Mimer internal error when querying `recRecursive`
```agda
open import Agda.Primitive
open import Relation.Binary.Bundles using (Setoid)

module _ {ℓ₁ ℓ₂ : Level} (sto : Setoid ℓ₁ ℓ₂) where

data D : Set {!!} where  -- C-c C-a
  c : D
```
Mimer in the hole gives an internal error here: https://github.com/agda/agda/blob/7eb6303e0c9777a70de565c5de1f78c656817283/src/full/Agda/TypeChecking/Monad/Base.hs#L2961-L2964

### PR DESCRIPTION
**Pull request by UlfNorell**
Fixes #7133

_Note to future git-bisecters_

The missing mutual information caused some functions to not be considered for projection-likeness, so if you end up blaming this commit, there might be a bug with projection-likeness.

### CODE REVIEW

File: src/full/Agda/TypeChecking/Positivity.hs [hunk 1]
```diff
@@ -199,26 +207,13 @@ checkStrictlyPositive mi qset = do
...
-    setMut :: [QName] -> TCM ()
-    setMut [] = return ()  -- nothing to do
-    setMut qs = forM_ qs $ \ q -> do
-      reportSLn "tc.pos.mutual" 10 $ "setting " ++ prettyShow q ++ " to (mutually) recursive"
-      setMutual q qs
-      -- TODO: The previous line produces data of quadratic size
-      -- (which has to be processed upon serialization).  Presumably qs is
-      -- usually short, but in some cases (for instance for generated
-      -- code) it may be long. Wouldn't it be better to assign a
-      -- unique identifier to each SCC, and avoid storing lists?
```
Comment (andreasabel) [inline src/full/Agda/TypeChecking/Positivity.hs:220]: Shouldn't this TODO be preserved?

**Review by andreasabel — COMMENTED** [review]
Looks good!

Should we maybe keep the TODO note here?  Seems still valid after the fix.

File: src/full/Agda/TypeChecking/Positivity.hs (hunk 1 above)
Comment (UlfNorell) [reply src/full/Agda/TypeChecking/Positivity.hs:220]: Yes. I put it on `setMutual`: 668822a23

Comment (andreasabel) [reply src/full/Agda/TypeChecking/Positivity.hs:220]: Thanks!
